### ISSUE TITLE
cursor fetch long decimal raise conversion error: InvalidOperation

### ISSUE THREAD

**Issue by zhuobao** [mkleehammer/pyodbc#126]
when connecting to teradata and run the below query:

``` python
 csr = con.execute('select 12344556778899 as idx;')
 csr.fetchall()

---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
<ipython-input-65-332750c4d735> in <module>()
----> 1 csr.fetchall()

InvalidOperation: [<class 'cdecimal.ConversionSyntax'>]

```

seems pyodbc has difficulty converting long decimal from teradata to python data types.
any solution?

system: redhat 7
python: Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
IPython 4.1.2
pyodbc: 3.0.10

**Comment by mkleehammer** [comment]
Well, first I'm surprised it chose decimal instead of int.  I suppose it returns all values greater than some constant as decimal?

Because there are so many driver bugs with the binary decimal struct, pyodbc requests it as text and calls the decimal.Decimal constructor.  This of course leads down a rabbit hole - using text leads to language issues such as "," instead of "." which the decimal class does not deal with.  I replace them.

When you select this number in a teradata client, what does it show?  Is it inserting commas?  Perhaps I need to smarten it up to see if both are present and only convert if the comma is the *last* item.

**Comment by femibyte** [comment]
Any progress on on how one can get a workaround for this ? I'm getting the same error...

**Comment by mkleehammer** [comment]
Can you test this with pyodbc 4.0.1 and get a trace?  I'd like to see what the format of the string is.

I'm tempted to attempt reading decimals as binary structures, but some databases don't set them right leading to garbage.  I suppose I could default to doing so and use a flag to turn it off until drivers get fixed.

**Comment by mkleehammer** [comment]
Actually, the issue is going to be related to Unicode.  Teradata is sending UTF-8, I think, and I'm expecting UTF-16.  This is a place in 4.0 that didn't get updated with correct Unicode handling.  Working on it now.

**Comment by mkleehammer** [comment]
Is it possible for you to test with the fix-126 branch?  I think I have it fixed but I don't have a system that was failing to test against.
