### ISSUE TITLE
PyODBC Connection Issue on Apache 2.4

### ISSUE THREAD

**Issue by varunboyapati** [mkleehammer/pyodbc#147]
I was running my application under  Apache 2.4 and mod_wsgi. The ODBC connection works fine using Python Shell and Same causing issue when working under Apache.

Below is the error message - 

Error: ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')

I had set up the environment variable on bashrc. ( Didn't helped me )

But I do have the ODBC driver set up on the Linux system and was able to connect to the same using Python Shell. 

Please help on this.

**Comment by mkleehammer** [comment]
This is really an environment issue, so I'll do what I can.  It's been years since I've used mod_wsgi.  First, mod_wsgi is C code and is compiled against a particular version of Python.  Are you sure they are the same?

The second most common error would be that the ODBC libraries are not available in the Apache library path.  You'd have to do something like this: http://stackoverflow.com/questions/7847305/how-to-set-ld-library-path-individually-for-django-web-sites-with-apache-and-mod

I had to work through this years ago but I forgot what I did.  I'm going to have to close this for now and refer you to the mod_wsgi support though.  If you do find anything, it would be great if you would add a link to it here for the next person, though.  Good luck.
