### ISSUE TITLE
Turn Transactions off

### ISSUE THREAD

**Issue by danturn** [mkleehammer/pyodbc#149]
Hi Michael, 

Is there any way to turn off transactions in pyodbc?

thanks

Dan

**Comment by mkleehammer** [comment]
You are looking for "autocommit".  You can turn autocommit on when creating the connection by passing "autocommit=True" to the connect function.  Once you have a connection, you can change the status using the `autocommit` property.

```
cnxn = pyodbc.connect(..., autocommit=True)

cnxn.autocommit = False
cnxn.autocommit = True
```

This does exactly what you want, but be sure it is what you need.  The connections begin with autocommit off which ensures code is maintanable since an explicit commit is required.  If you start with one update and later add two, explicit commits will always work:

```
cnxn.execute(...)   # original code
cnxn.execute(...)   # a second update someone adds later
cnxn.commit()
```

With autocommit turned on, if the original code succeeds but the 2nd fails, the first update will be committed.  I know this is obvious, but it is common to not like autocommit=False when starting out and grow to like it over time.

Either way, good luck!

**Comment by danturn** [comment]
Hi Michael, thanks for that, 

I'd really rather disable them completely as we only issue single read statements and with the wan latency we're dealing with sending the 2 additional transaction manager packets adds considerable overhead. If that's not possible then no worries!

keep up the good work
Dan

**Comment by mkleehammer** [comment]
Clearly you know what you are doing (I get this question a lot from those that don't), so autocommit is definitely what you are looking for.

**Comment by danturn** [comment]
thanks! that does do exactly what i need 
dan
