### ISSUE TITLE
Add support for SQLCancel

### ISSUE THREAD

**Issue by FunkyLoveCow** [mkleehammer/pyodbc#158]
Would it be possible to add support for SQLCancel? 

It appears a patch was created by GoogleCodeExport in another repository, but that repository seems maintained.

https://github.com/Ferritas/pyodbc/issues/340

**Comment by mkleehammer** [comment]
I can.  To make sure I understand - how do you expect it to be used?  Pass the cursor to another thread which cancels after a timeout or a button is clicked, etc.?

(BTW, if a timeout, don't forget that you can set a timeout on the connection to raise a timeout error instead of scheduling your own cancel.)

**Comment by FunkyLoveCow** [comment]
My use case is that a user will fire off a query in a QT UI. If the user gets impatient, they'll click "cancel/stop" etc and the query would be stopped. 

In this scenario, the user is running queries that can be very long, so we don't set a timeout on the connection.

**Comment by LeoPiero** [comment]
Any word on this?  I'm building a script to execute long running jobs.  I would like to have a thread that checks for a trigger and then would send a cancel to the job.  If I'm not mistaken the only way to do this now would be to kill the job thread.

**Comment by FunkyLoveCow** [comment]
Just curious, was this supposed to be closed?

**Comment by mkleehammer** [comment]
Yes, Cursor.cancel() was added in the commit referenced above, 5eb9d0d, and released in the latest release.
