### ISSUE TITLE
Failing to make pyodbc-4.0 works on excel in 64 bit mode

### ISSUE THREAD

**Issue by stonebig** [mkleehammer/pyodbc#176]
see http://stackoverflow.com/questions/41525246/fail-to-make-pyodbc-4-0-64bit-find-excel-driver-windows10-64bit

I don't find how to tweak this code so it works also with Python-3.6 64 bit. 

What shall I do to make pyodbc work on 64 bit Python ?

`````
import pyodbc
import os
# DATABASE CONNECTION
filename = 'C:\\WinPython\\basedir36\\buildZero\\winpython-64bit-3.6.x.1\\notebooks\\test.xls'
assert os.path.exists(filename)

CNXNSTRING = 'Driver={Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)};DBQ=%s;READONLY=FALSE' % filename
print ('CNXNSTRING is ', CNXNSTRING)
cnxn = pyodbc.connect(CNXNSTRING, autocommit=True)
````

**Comment by Lexcon** [comment]
This is probably not a pyODBC issue. I assume you need to install the driver for the 64 bits system. See the download below. Note that it mentions 'access' driver but it mentions xls and xlsx files too:

https://www.microsoft.com/en-us/download/details.aspx?id=13255

**Comment by stonebig** [comment]
As I have an Office 32 bit, the 64 bit driver doesn't want to install... This Microsoft problem seems without solution.. https://twitter.com/zooba/status/818236978600689665

**Comment by Lexcon** [comment]
Is it am option to use 32bit python?


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: stonebig <notifications@github.com> 
Datum: 09-01-17  20:31  (GMT+01:00) 
Aan: mkleehammer/pyodbc <pyodbc@noreply.github.com> 
Cc: Lexcon <robert@dotdata.nl>, Comment <comment@noreply.github.com> 
Onderwerp: Re: [mkleehammer/pyodbc] Failing to make pyodbc-4.0 works on excel in
  64 bit mode (#176) 

As I have an Office 32 bit, the 64 bit driver doesn't want to install... This Microsoft problem seems without solution.. https://twitter.com/zooba/status/818236978600689665

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mkleehammer/pyodbc","title":"mkleehammer/pyodbc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mkleehammer/pyodbc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stonebig in #176: As I have an Office 32 bit, the 64 bit driver doesn't want to install... This Microsoft problem seems without solution.. https://twitter.com/zooba/status/818236978600689665"}],"action":{"name":"View Issue","url":"https://github.com/mkleehammer/pyodbc/issues/176#issuecomment-271383299"}}}

**Comment by stonebig** [comment]
If you whish to do a part of your worfklow in 64 bit, that's a bit painfull as:
-  you have to split your workflow in 2,
- you have to take care that the Python 32 bit part don't mess up with the 64 bit part.

... complexity, when the "order winner" point of Python is supposed to be simplicity.

**Comment by Lexcon** [comment]
This has nothing to do with python. No 32 bit app will communicate to a 64 bit app over odbc like that.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: stonebig <notifications@github.com> 
Datum: 09-01-17  20:45  (GMT+01:00) 
Aan: mkleehammer/pyodbc <pyodbc@noreply.github.com> 
Cc: Lexcon <robert@dotdata.nl>, Comment <comment@noreply.github.com> 
Onderwerp: Re: [mkleehammer/pyodbc] Failing to make pyodbc-4.0 works on excel in
  64 bit mode (#176) 

If you whish to do a part of your worfklow in 64 bit, that's a bit painfull as:

you have to split your workflow in 2,
you have to take care that the Python 32 bit part don't mess up with the 64 bit part.

... complexity, when the "order winner" point of Python is supposed to be simplicity.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mkleehammer/pyodbc","title":"mkleehammer/pyodbc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mkleehammer/pyodbc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stonebig in #176: If you whish to do a part of your worfklow in 64 bit, that's a bit painfull as:\r\n-  you have to split your workflow in 2,\r\n- you have to take care that the Python 32 bit part don't mess up with the 64 bit part.\r\n\r\n... complexity, when the \"order winner\" point of Python is supposed to be simplicity.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mkleehammer/pyodbc/issues/176#issuecomment-271387518"}}}
