### ISSUE TITLE
Does not work prepare SELECT IN (list - prepare value)

### ISSUE THREAD

**Issue by itpooh** [mkleehammer/pyodbc#189]
curs.execute("SELECT 1 WHERE 1 IN (?)", [1,2,3,4])
_pyodbc.ProgrammingError: ('The SQL contains 1 parameter markers, but 4 parameters were supplied', 'HY000')_

**Comment by keitherskine** [comment]
You can't pass a Python list as a SQL parameter.  The parameters have to correspond to single values - strings, integers, floats, datetime.date, etc.  See the list of available object types on the wiki page https://github.com/mkleehammer/pyodbc/wiki/Data-Types , look for the "Python Datatype" column in the first table there.

**Comment by mkleehammer** [comment]
There are three issues:
* pyodbc doesn't have array bindings yet
* I don't think ODBC / SQL Server will actually process an array in an IN statement which is why I didn't bother with the array bindings.
* pyodbc is unpacking the list since that is how the DBAPI requires parameters.

I'll retest IN clauses with array parameters, but I'm pretty sure SQL Server wouldn't take it.  If it does, I'd like to have it myself so I'll add it immediately.  If not I'll update this.

I end up constructing the IN clause like so:

    params = [...]
    qmarks = ','.join('?' * len(params))
    sql = "select ... in {}".format(qmarks)

I'm not a fan, but I was pretty sure it was required.  I'll check again because *I'd* really like to not have to do that also.

The last point is that the DBAPI requires execute only have 2 parameters, (sql, params), where params is a sequence of parameters.  When pyodbc sees a single parameter that is a sequence, for compatibility with the API it will unpack it.  For those cases wrap it in another sequence:

  execute("...", ( [1,2,3,4] ))

If you are working in a section of code that has a variable number of parameters and you are generating SQL, etc. and you don't want to special case this kind of code, simply *always* use an extra sequence.  This works fine:

    execute("select * from u where id=?", (1))

Obviously when writing by hand, which is most of the time, I prefer not to use the outer sequence.

**Comment by mkleehammer** [comment]
OK, it appears that it is not possible to solve this: [Arrays and Lists in SQL Server](http://www.sommarskog.se/arrays-in-sql.html)

I'm not sure he is the expert, but I haven't seen anything contradicting it and it matches my testing.

I wish it wasn't the case or that SQL Server had a better operator like some other databases.  In the meantime, you'll need to format the SQL yourself.

Remember, **do not** put the values into the where clause, just question marks.  You don't need [SQL injection vulnerabilities](https://en.wikipedia.org/wiki/SQL_injection).

**Comment by joaoe** [comment]
Howdy. My two cents.

Microsoft SQL supports TABLE variables, which can carry an arbitrary amount of records.

Example:
```
-- Dummy table to join as example
CREATE TABLE MyTable(n INTEGER);
INSERT INTO MyTable VALUES (1),(2),(3);

-- Example of how to embed a dynamic list of values into a query
SELECT *
From MyTable r, (VALUES (2), (3)) AS v([n])
WHERE r.n = v.n;

-- Further extending the previous example with a TABLE variable
declare @myList TABLE(n INTEGER);
INSERT INTO @myList VALUES (1), (2);
SELECT *
From MyTable r, @myList v
WHERE r.n = v.n;
```
But I think ODBC does not expose an API to be able to bind arrays to table variables.
