### ISSUE TITLE
pyodbc 4.0.5 regression: cannot execute Python 2.7 unicode string

### ISSUE THREAD

**Issue by zzzeek** [mkleehammer/pyodbc#193]
Python 2.7, SQL Server ODBC drivers 11, 13, Succeeds on 4.0.3, fails on 4.0.5:

```
import pyodbc
conn = pyodbc.connect("uid=scott;pwd=tiger;server=192.168.122.135,1213;database=test;driver=ODBC Driver 11 For SQL Server")
cursor = conn.cursor()
cursor.execute(u"select 'hi'")
assert cursor.fetchone()[0] == 'hi'

```

Error:

    pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near '0xffff'. (102) (SQLExecDirectW)")

Executing "select 'hi'" without the 'u' works fine.

**Comment by zzzeek** [comment]
downstream SQLAlchemy issue: https://bitbucket.org/zzzeek/sqlalchemy/issues/3910/programmingerror-raised-with-pyodbc-405

**Comment by mkleehammer** [comment]
Thanks.  There's even a test so I'm not sure what happened.  Fixed in 4.0.6.  Binary wheels are already uploaded for macOS and Windows.

**Comment by mkleehammer** [comment]
See #191 for details.

**Comment by zzzeek** [comment]
thanks for the fast turnaround!   for the test, if you revert the change does the test fail ?

**Comment by mkleehammer** [comment]
Yes, but I didn't just revert to fix as I needed the change.

The core issue that started 4.0.3 is that I discovered that some DBs like PostgreSQL and MySQL will send column names (SQLDescribeCol) in UTF-16LE *regardless* of the database / client encoding.  Undocumented as far as I can tell.  Since the encoding is configurable, I had to add a 3rd encoding configuration which now defaults to UTF-16LE.

During this emergency change I accidentally passed a buffer length instead of a character length.
