### ISSUE TITLE
Database locks while running pyodbc statement

### ISSUE THREAD

**Issue by SquareWaffles** [mkleehammer/pyodbc#198]
When running large queries through pyodbc, the database (not just the selected tables) becomes locked for all users.

For example pyodbc would be running the following query:
```
SELECT FieldA, FieldB, geometry::UnionAggregate(ShapeBuffer) AS ShapeDissolve
INTO   Tmp_Table
FROM (SELECT FieldA, FieldB, Shape.STBuffer(10) AS ShapeBuffer FROM FeatureClass) AS TblA
GROUP BY FieldA, FieldB
```

While the above query is running which takes several minutes (large and complex feature class), we cannot connect to the database using SQL Server Management Studio or ArcGIS.  Arc will freeze and SSMS gives the error: "Lock request time out period exceeded. (Microsoft SQL Server, Error: 1222)".

**Comment by mkleehammer** [comment]
That does sound weird, but it is not a pyodbc issue per se - it is simply passing the query to the database and you should see similar behavior if you ran the query in SQL Server Management Studio.

Is Tmp_Table an actual temporary table?  If so, SQL Server will create it in the tempdb and I believe there are more locking issues there.  If so, try creating a work table in your actual DB and select into it instead, at least to test the theory.

One thing pyodbc does is start a transaction automatically, but I don't think you'll see any difference if you set `cnxn.autocommit=True` before running the query, but you might try it.

Otherwise it could be that you simply are out of CPU or memory on the database server.  Have you checked that?

**Comment by keitherskine** [comment]
"SELECT ... INTO ..." puts more than just one lock on the database in SQL Server.  Generally, you can't create other objects in the database whilst this kind of statement is running, which might explain the timeout you're getting.  Hence, "SELECT ... INTO ..." is something I try to avoid for large amounts of data.  Try running your code above in two steps, as follows:
```sql
-- generate the temporary table (this should be very quick)
SELECT TOP 0 FieldA, FieldB, geometry::UnionAggregate(ShapeBuffer) AS ShapeDissolve
INTO Tmp_Table
FROM (SELECT FieldA, FieldB, Shape.STBuffer(10) AS ShapeBuffer FROM FeatureClass) AS TblA
GROUP BY FieldA, FieldB;

-- populate the temporary table
INSERT INTO Tmp_Table
SELECT FieldA, FieldB, geometry::UnionAggregate(ShapeBuffer) AS ShapeDissolve
FROM (SELECT FieldA, FieldB, Shape.STBuffer(10) AS ShapeBuffer FROM FeatureClass) AS TblA
GROUP BY FieldA, FieldB
```

**Comment by SquareWaffles** [comment]
Thank you @mkleehammer and @keitherskine, you were both correct.  Tmp_Table is an actual table and `cnxn.autocommit=True` didn't effect the locking.  But generating the table with `Top 0` and then running `INSERT INTO` did release the database lock.  Thanks again.
