### ISSUE TITLE
MSSQL: string with large unicode character is truncated on insert

### ISSUE THREAD

**Issue by dirkjonker** [mkleehammer/pyodbc#221]
When inserting a string containing emoji characters into a `NVARCHAR` column in MSSQL using FreeTDS 1.00.26 + unixODBC 2.3.4 + Python 3.5 + pyodbc 4.0.15 and the default connection properties (as per recommendation in the documentation):

```
>>> text = 'Test 1 2 3 😂  foo bar'

>>> cursor.execute("CREATE TABLE dbo.unicode_test (val NVARCHAR(100));")

>>> cursor.execute("INSERT INTO dbo.unicode_test (val) VALUES (?);", (text,))

>>> cursor.execute("SELECT TOP (1) val FROM dbo.unicode_test;")

>>> print(cursor.fetchone())
('Test 1 2 3 😂  foo ba', )
```

As you can see, the final "r" is dropped. For each extra emoji in the text, more characters seem to be truncated (N emoji = last N characters are dropped).

This seems to happen when pyodbc is converting the UTF8 string when executing the INSERT statement, since the database does not contain the final character (I checked this with other tools). 

When I convert the text to UTF-16-LE using `text.encode('utf_16_le')`, there is no truncation.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue under PyCharm Community Edition 2016.3.3 with Python 3.6 and pyodbc 4.0.15. My code ...

```python
import pyodbc
print(pyodbc.version)
cnxn = pyodbc.connect(
    r"DRIVER=ODBC Driver 11 for SQL Server;"
    r"SERVER=(local)\SQLEXPRESS;"
    r"DATABASE=myDb;"
    r"Trusted_Connection=yes;")
crsr = cnxn.cursor()

text = 'test 1 2 3 😂 foo bar'

crsr.execute("CREATE TABLE #unicode_test (val NVARCHAR(100))")
crsr.execute("INSERT INTO #unicode_test (val) VALUES (?)", text)

value = crsr.execute("SELECT TOP 1 val FROM #unicode_test").fetchval()
print(value)

crsr.close()
cnxn.close()
```

... produces ...

```none
C:\Users\gord\PycharmVirtualenvs\py3pyodbc\Scripts\python.exe C:/Users/gord/PycharmProjects/pyodbc_issue_221/main.py
4.0.15
test 1 2 3 😂 foo bar

Process finished with exit code 0
```

I also get the same results if I use a Unicode escape instead of the emoji character

```python
text = 'test 1 2 3 \U0001F602 foo bar'
```

**Comment by gordthompson** [comment]
I was able to reproduce the issue on Xubuntu 16.04 with unixODBC and FreeTDS_ODBC from the Ubuntu repositories. The text, which I defined as

```python
text = 'test 1 2 3 \U0001F602 foo bar'
```

is truncated when it is being saved. SQL Profiler shows

```sql
declare @p1 int
set @p1=1
exec sp_prepexec @p1 output,N'@P1 NVARCHAR(20),@P2 NVARCHAR(13)',N'INSERT INTO [unicode_test] ([val], [source]) VALUES (@P1,@P2)',N'test 1 2 3 😂 foo ba',N'Linux/FreeTDS'
select @p1
```

which is interesting because the parameter is declared as `NVARCHAR(20)` but

```none
test 1 2 3 😂 foo ba
```

is only 19 characters long.

**Comment by gordthompson** [comment]
Another data point: I repeated the test under Xubuntu 16.04, this time using the latest Microsoft ODBC Driver for Linux. It failed with

```none
Traceback (most recent call last):
  File "unicode_test.py", line 8, in <module>
    crsr.execute("INSERT INTO [unicode_test] ([val], [source]) VALUES (?,?)", (text, 'Linux/MSODBC'))
pyodbc.DataError: ('22001', '[22001] [Microsoft][ODBC Driver 13 for SQL Server]String data, right truncation (0) (SQLExecDirectW)')
```

Once again, I was using

```python
text = 'test 1 2 3 \U0001F602 foo bar'
```

No error occurred when the text string was

```python
text = 'gord'
```

**Comment by dirkjonker** [comment]
Thanks @gordthompson for all the extra testing!
The 22001 error means something like: you said you were binding x characters but you gave me more. I'll see if I can reproduce on Linux using the Microsoft driver and run an ODBC trace.

**Comment by dirkjonker** [comment]
The trace from running that same code on Centos 7 + unixODBC 2.3.1 + Microsoft ODBC Driver 13.1.4.0

```
[ODBC][2144][1490196227.260658][SQLPrepareW.c][165]
                Entry:
                        Statement = 0x2e64a00
                        SQL = [INSERT INTO test.dbo.unicode_test (val) VALUES (?)][length = 50]
[ODBC][2144][1490196227.260724][SQLPrepareW.c][340]
                Exit:[SQL_SUCCESS]
[ODBC][2144][1490196227.260784][SQLNumParams.c][144]
                Entry:
                        Statement = 0x2e64a00
                        Param Count = 0x7ffec241b610
[ODBC][2144][1490196227.260836][SQLNumParams.c][228]
                Exit:[SQL_SUCCESS]
                        Count = 0x7ffec241b610 -> 1
[ODBC][2144][1490196227.260898][SQLBindParameter.c][217]
                Entry:
                        Statement = 0x2e64a00
                        Param Number = 1
                        Param Type = 1
                        C Type = -8 SQL_C_WCHAR
                        SQL Type = -9 SQL_WVARCHAR
                        Col Def = 20
                        Scale = 0
                        Rgb Value = 0x7f37219600a0
                        Value Max = 42
                        StrLen Or Ind = 0x2e38718
[ODBC][2144][1490196227.261059][SQLBindParameter.c][397]
                Exit:[SQL_SUCCESS]
[ODBC][2144][1490196227.261297][SQLExecute.c][187]
                Entry:
                        Statement = 0x2e64a00
[ODBC][2144][1490196227.262069][SQLExecute.c][348]
                Exit:[SQL_ERROR]
                DIAG [22001] [Microsoft][ODBC Driver 13 for SQL Server]String data, right truncation
```

It seems that SQLBindParameter is called with a length of 20, which is the correct Python length of the utf-8 string **which counts the emoji as a single character**. However, the emoji in UTF-16 encoding is 4 bytes, which is double the size of a regular character.

**Comment by engagex** [comment]
Hi @dirkjonker 

I'm having a similar issue, but in my case, the issue is with a column NVARCHAR(MAX) on SQL SERVER.
I'm trying to insert a large content to it, that has a lot of quotes/doublequotes, and I'm using binding for the variable when calling the procedure to insert.

The value is in: https://gist.github.com/engagex/f24907825ec23b9303897133c7784e32
The code I'm using to call it:
```
sql = '{CALL PR_XYZ(@Value=?)}'
params = (n["Content"])
cursor.execute(sql, params)
```

The stack trace: 

2|egx-int- | Traceback (most recent call last):
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/dbEGX.py", line 16, in getConnection
2|egx-int- |     yield cursor
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/dbEGX.py", line 75, in insertKnewinNews
2|egx-int- |     cursor.execute(sql, params)
2|egx-int- | pyodbc.DataError: ('22001', '[22001] [Microsoft][ODBC Driver 13 for SQL Server]String data, right truncation (0) (SQLPutData)')
2|egx-int- | During handling of the above exception, another exception occurred:
2|egx-int- | Traceback (most recent call last):
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/__main__.py", line 142, in <module>
2|egx-int- |     main()
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/__main__.py", line 80, in main
2|egx-int- |     processQueries(queryParams)
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/__main__.py", line 133, in processQueries
2|egx-int- |     return processQueries(queryParams,(offset+10))
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/__main__.py", line 133, in processQueries
2|egx-int- |     return processQueries(queryParams,(offset+10))
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/__main__.py", line 129, in processQueries
2|egx-int- |     dbEGX.insertKnewinNews(result["hits"], queryParams["companyId"])
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/dbEGX.py", line 75, in insertKnewinNews
2|egx-int- |     cursor.execute(sql, params)
2|egx-int- |   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
2|egx-int- |     self.gen.throw(type, value, traceback)
2|egx-int- |   File "/home/nodeuser/node/dev/egx-int-knewin/dbEGX.py", line 18, in getConnection
2|egx-int- |     error, = err.args
2|egx-int- | ValueError: too many values to unpack (expected 1)

Do you have any idea of what could it be? It's happening on linux ubuntu 16.04 on AWS, python 3 and pyodbc (4.0.16)

**Comment by dtiziani** [comment]
Actually I've trimmed it to being caused by a smiley (UTF-8) #246 if you could help me

**Comment by mkleehammer** [comment]
I wonder if this is related to #213.

**Comment by gordthompson** [comment]
> I wonder if this is related to #213.

I don't believe so. In #213 the communication between the client and the server is correct; it's simply a matter of dealing with multiple calls involving parameters of varying lengths. This issue is about an apparent miscommunication between the client and the server, clearly related to the fact that some UTF-16LE encoded characters are represented by more than two (2) bytes.

As mentioned earlier, this issue does not occur on Windows clients, leading me to suspect that it is related to unixODBC. The issue was first reported as occurring with unixODBC 2.3.4, which is current, so it's not just a case of a Linux repository installing an old version (e.g., the Ubuntu repositories still seem to be stuck on 2.3.1). A follow-up post showed the ODBC trace from a Centos 7 box which included

```
[ODBC][2144][1490196227.260898][SQLBindParameter.c][217]
                Entry:
                        Statement = 0x2e64a00
                        Param Number = 1
                        Param Type = 1
                        C Type = -8 SQL_C_WCHAR
                        SQL Type = -9 SQL_WVARCHAR
                        Col Def = 20
                        Scale = 0
                        Rgb Value = 0x7f37219600a0
                        Value Max = 42
                        StrLen Or Ind = 0x2e38718
```

Comparing that to an ODBC trace under Windows ...

```
main            14e0-854    EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x022C1A60
        UWORD                        1 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                       -8 <SQL_C_WCHAR>
        SWORD                       -9 <SQL_WVARCHAR>
        SQLULEN                   21
        SWORD                        0 
        PTR                0x01D64530
        SQLLEN                    42
        SQLLEN *            0x005C9454 (42)
```

... it looks like the Windows call is making allowances for the extra 2 bytes by declaring the parameter length as 21 "effective two-byte characters" (`SQLULEN 21`) while the Linux call appears to be specifying the actual number of Unicode characters (`Col Def = 20`). Perhaps related is the "magic number" 42 that appears in both cases (`Value Max = 42` under Linux, `SQLLEN 42` under Windows).

I guess the question is: Who is responsible for taking care of that bit of accounting? Does the ODBC spec say anything specific about Unicode encoding, especially with regard to UCS-2 (where every supported character is represented by exactly 2 bytes) versus UTF-16 (where some characters are represented by more than 2 bytes)?

**Comment by v-chojas** [comment]
> I guess the question is: Who is responsible for taking care of that bit of accounting? Does the ODBC spec say anything specific about Unicode encoding, especially with regard to UCS-2 (where every supported character is represented by exactly 2 bytes) versus UTF-16 (where some characters are represented by more than 2 bytes)?

The ODBC spec only mentions that the "column size" parameter is the "size in characters", and gives the example that "the column size of a single-byte character column defined as CHAR(10) is 10". Thus, it seems this is left to the DBMS to decide; in the case of SQL Server, an nvarchar(n) column in SQL Server can store exactly n UCS-2 characters:

https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql

Thus, a UTF-16 character which is actually a surrogate pair takes 2 "characters" of storage in an nvarchar(n) column, much like MBCS characters will count towards multiple "characters" of a varchar(n).

I do not think this issue is due to unixODBC, since it just passes the column size parameter from the application to the driver; it is related to how pyodbc is calculating it.

**Comment by v-chojas** [comment]
pyodbc is using PyUnicode_GET_SIZE() to calculate the column size. This returns the number of code units, so on Windows which uses UTF-16 exclusively, surrogate pairs count as 2, and thus the column size is calculated correctly at least for SQL Server which also uses UTF-16.

On Linux, where Python normally uses UTF-32, all code points are equivalent to code units, which leads it to calculate a "true" Unicode-character count of 1, even for those which would be surrogate pairs in UTF-16, but this disagrees with what SQL Server's encoding requires.

**Comment by mkleehammer** [comment]
So, for Python 3 it sounds like PyUnicode_GetLength is the fix.

Does anyone see anything useful in Python 2.7?  The 3.6 GetLength, which is documented as being the number of code points, is returning `obj->length`.  That field exists in 2.7, but the code in unicode_resize appears to set it to the number of Py_UNICODE elements, which is what we're already using.

**Comment by mkleehammer** [comment]
Actually, this brings up something else I wanted to ask @v-chojas.  We are talking about the "column size" here and not the byte size, which we know without a doubt.  Another open issue is that pyodbc is sending exact string lengths (ignore this bug for now) and causing SQL Server to cache a new plan for each execute of the same SQL with different string parameters.  Would solving that issue automatically fix this one?

**Comment by v-chojas** [comment]
@mkleehammer  PyUnicode_GetLength won't work either, because (at least for SQL Server, and other DBMSs which use UTF-16 wvarchar) the driver is expecting the number of UTF-16 _code units_ and not _code points_ (which is equivalent to UTF-32 code units).

> Another open issue is that pyodbc is sending exact string lengths (ignore this bug for now) and causing SQL Server to cache a new plan for each execute of the same SQL with different string parameters. Would solving that issue automatically fix this one?

If "solving that issue" means binding parameters with the column size given to it by the server from SQLDescribeParam/Col/otherwise, then *yes*. E.g. an nvarchar(300) will result in binding a column size of 300. My PR which adds setinputsizes() will also fix this if the user sets the size to a suitable value for the column.

**Comment by mkleehammer** [comment]
Quite a few years back I tried using SQLDescribeParam but it was very, very slow.  At that time it added a network round trip to send the query to the server for parsing.  I believe SS has an optimization to avoid extra trips now (the other issue has the details), but I'm worried about a major performance regression for other drivers.  (Though maybe they need to step up and optimize?)

Should we try always using SQLDescribeParam and see if we can optimize later by caching a  statement --> sizes map with the cnxninfo (which is cached per-connection-string)?

**Comment by v-chojas** [comment]
You could make the use of SQLDescribeParam optional; i.e. the default is to bind with the string length (in UTF-16 code units, so this still needs to be fixed) but setting cursor.detect_metadata (or similar) option will cause it to use SQLDescribeParam. Of course, if setinputsizes() is set, that will override/bypass this.

Using SQLDescribeParam carries overhead (even for SQL Server) so makes sense if doing multi-row inserts; but for single-row, I think one of the other options will be better.

I don't remember exactly but I recall there is certainly a way to convert a string into UTF-16 and get its code-unit-length to pass into SQLBindParameter, so even if it uses exact string lengths, it will be the _correct_ exact string length... I will look into trying to fix this.

**Comment by sn4kebite** [comment]
Any update on this? It's still an issue as of 4.0.23. Encoding the string as UTF-16-LE works, but that means applying that workaround all over the place, which is not ideal.

**Comment by bityob** [comment]
Any updates on this? 

For Python 2.7, I didn't find yet a solution. 

We can't convert it to utf-16-le because pyodbc "encode" it again to bytes, and it fails because of the defualt encoding issue in Python2 which is ASCII

**Comment by bityob** [comment]
Update - 

Verified it now with version 4.0.26 (Python 2.7.15) and it's working great

Thanks

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
