### ISSUE TITLE
Azure DataWarehouse 

### ISSUE THREAD

**Issue by colin-streicher** [mkleehammer/pyodbc#241]
ODBC - 13.0.4 ( the latest MS one ) 
pyodbc - 4.0.16.0
python2.7
64-bit everything

I am running pyodbc on Linux, mostly ubuntu, the odbc version is the latest from MS. In general, it works really well, but I am having an issue that I am having a difficult time reproducing. 

In all of the code we are running, there are many thousands of queries running against a single database, after a few days, we see queries slow down significantly eventually causing me to have to pause/resume which seems to clear it up.
Though it may be something I can solve on the database side, I've solved similar problems with the same database ( different codebase ) by adding explicit closes when the code completes or raises an exception. 

I went through the code, but I am weak on C++, is there any situation where a dead connection could be left executing? 
I am interested in anyone's input on this, I know it is likely on the database side, but on the off-chance there is a connection leaking somewhere, I'm opening this issue.

**Comment by gordthompson** [comment]
Just a note re:

> ODBC - 13.0.4 ( the latest MS one )

The latest version is actually 13.1.7. The [installation instructions](https://docs.microsoft.com/en-us/sql/connect/odbc/linux/installing-the-microsoft-odbc-driver-for-sql-server-on-linux) are a bit out of date (ref: [here](https://github.com/mkleehammer/pyodbc/issues/238#issuecomment-301608809))

**Comment by colin-streicher** [comment]
Ok, 
My version is $ pacman -Q msodbcsql
msodbcsql 13.1.6.0-1

I guess I'm behind by one minor release, but I don't believe this would cause the issue.

**Comment by v-chojas** [comment]
Do the queries involve string parameters of widely-varying lengths? If so, perhaps the performance degradation is due to the proliferation of many execution plans in the cache, as mentioned in https://github.com/mkleehammer/pyodbc/issues/213 . I have some suggestions to try in that issue.

Another potential cause, also related to the plan cache, is that prepared statements will remain allocated and usable on the server until PyODBC's Cursor objects are either garbage-collected or the close() method is called. Ensure that you are closing the Cursors after using them in your application.
