### ISSUE TITLE
Support for returning query execution status on "cursor.execute(sql)"

### ISSUE THREAD

**Issue by CNiallDemensha** [mkleehammer/pyodbc#243]
- Python: 2.7
- pyodbc: 3.0.10
- OS: Windows
- DB: 
- driver: Teradata

### Issue
When a query is run in Teradata Client, the status of execution, for example, 

> CREATE TABLE completed. 0 rows processed. Elapsed time = 00:00:19

is displayed. Is it possible to make `cursor.execute(sql_code)` return such a message?

Errors in execution can be managed through error handling, but details on **successful** execution of query will be helpful. Is this already possible?

Thanks.

**Comment by mkleehammer** [comment]
Not really.  There isn't a defined ODBC set of data for this, but it is pretty easy to get any of it:

First, you know it was successful or an error would have been raised.

The easiest is the number of rows processed: `Cursor.rowcount`.   This is defined in the DB API specification and is discussed on the Cursor wiki page.  If the query is an insert, update, or delete statement it will be the number of rows affected.  Otherwise, like the create table here, it will be None.

If your application is always going to want the time, there are multiple ways of doing it, but one that is handy for more than that is "wrapping" the objects.  Write your own Connection wrapper that defers everything to the base class.  Have it wrap any cursors.  Then in the overridden cursor `execute`, take the time before and after calling the base class one.  This is also a good way to add debug logging, logging of long running queries, etc.
