### ISSUE TITLE
UTF-8 Issue while inserting - It fails

### ISSUE THREAD

**Issue by dtiziani** [mkleehammer/pyodbc#246]
I'm trying to call a procedure in Linux to a SQL Server, and I've tried all the combinations, but it fails. Tried setting the charset on the connectionstring, setting connection encoding, but it all fails.

The test case is simple: trying to insert the following value (it's UTF-8): ' 🇧🇷'
It fails with the following stacktrace:
```

  File "test.py", line 15, in getConnection
    yield cursor
  File "test.py", line 38, in testFailed
    cursor.execute(sql, params)
pyodbc.DataError: ('22001', '[22001] [Microsoft][ODBC Driver 13 for SQL Server]String data, right truncation (0) (SQLExecDirectW)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 40, in <module>
    testFailed()
  File "test.py", line 38, in testFailed
    cursor.execute(sql, params)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "test.py", line 17, in getConnection
    error, = err.args
ValueError: too many values to unpack (expected 1)

```

Can someone help me? 
Info:
Python3
pyodbc (4.0.16)

**Comment by mkleehammer** [comment]
I have been looking into this, but I don't have a solution just yet.  Here are some notes and links, but I haven't been able to make anything work.

The problem occurs with any character greater than 0xFFFF, which this emoji is (0x1_F1E7).  Windows and SQL Server started out using UCS2, which could not encode this character, but as of 2008 I thought were actually using UTF16-LE.

This article has good information: [Collation and Unicode Support | Microsoft Docs](https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support)

"To use the UTF-16 collations available in SQL Server 2017, you can select one of the supplementary characters _SC collations (Windows collations only) to improve searching and sorting of some Unicode characters." 

"Introduced in SQL Server 2012, a new family of supplementary character (SC) collations can be used with the data types nchar, nvarchar and sql_variant. For example: Latin1_General_100_CI_AS_SC"

It sounds like the minimum requirements may be:

* SQL Server 2012
* ODBC 3.7
* Use a collation ending with "_SC" (supplemental characters)

Also, "[s]upplementary characters are not supported for use in metadata, such as in names of database objects", so no emojis can be used as column names. 

Reference:

* [MS - Supplementary Characters](https://technet.microsoft.com/en-us/library/ms180942(v=sql.105).aspx)
* [Supplementary Characters in SQL Server](https://devio.wordpress.com/2012/05/13/supplementary-characters-in-sql-server/)

**Comment by mkleehammer** [comment]
Are you able to get this character into SQL Server using Management Studio? I'm using SQL Server 2012 and the following returns '??'

    create table x(t nvarchar(100))
    INSERT INTO x(t) VALUES ('🌀')
    select * from x;

The collation for the database is Latin1_General_100_CI_AS_SC.

**Comment by gordthompson** [comment]
@mkleehammer Your test code returns `??` because your string literal `'🌀'` is a VARCHAR literal. Using an NVARCHAR literal `N'🌀'` will cause your SELECT to return a single character, although the default font for datagrids in SSMS will not be able to display it properly.

Also, as mentioned [here](https://github.com/mkleehammer/pyodbc/issues/221#issuecomment-309241157), this is a Linux(+Mac?) issue; it does not occur when using pyodbc under Windows. Running the following code under PyCharm on Windows

```python
import pyodbc
import sys
print(sys.version)
print("pyodbc " + pyodbc.version)
conn_str = (
    r"DRIVER=ODBC Driver 11 for SQL Server;"
    r"SERVER=(local)\SQLEXPRESS;"
    r"DATABASE=myDb;"
    r"Trusted_Connection=yes;"
)
cnxn = pyodbc.connect(conn_str, autocommit=True)
crsr = cnxn.cursor()
crsr.execute("create table #x (t nvarchar(100))")
crsr.execute("INSERT INTO #x (t) VALUES (N'🌀')")
print(crsr.execute("select * from #x").fetchall())
crsr.close()
cnxn.close()
```

produces

```
C:\Users\gord\PycharmVirtualenvs\py3pyodbc\Scripts\python.exe C:/Users/gord/PycharmProjects/issue246/main.py
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
pyodbc 4.0.17
[('🌀', )]

Process finished with exit code 0
```

Notes: 

1. The above database is SQL Server 2014 using `SQL_Latin1_General_CP1_CI_AS` collation.

2. PyCharm is necessary when testing these issues under Windows because the Windows command prompt is notoriously bad at displaying Unicode, and IDLE cannot handle Unicode characters outside of the BMP.

**Comment by v-chojas** [comment]
Note that insertion of "high Unicode" characters requires special care in the case of using the Linux and Mac SQL Server drivers, in order to set the lengths correctly to avoid truncation. Please see https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/known-issues-in-this-version-of-the-driver  for more information.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
