### ISSUE TITLE
No Error If Connection Is Lost

### ISSUE THREAD

**Issue by BChip** [mkleehammer/pyodbc#248]
### Environment
- Python: Python 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] on linux2
- pyodbc: 3.1.1
- OS: Linux ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- DB: Microsoft Azure
- driver: {ODBC Driver 13 for SQL Server}

### Code
import pyodbc
import time
server = ''
database = ''
username = ''
password = ''
driver= '{ODBC Driver 13 for SQL Server}'

cnxn = pyodbc.connect('DRIVER='+driver+';PORT=1433;SERVER='+server+';PORT=1443;DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()

while True:
	with cursor.execute("INSERT INTO dbo.temperature (name, userid, temperature, humidity, recorded) VALUES ('Name', 'UA18082', 78, 75, GETDATE())"):
	    print ('Successfuly Inserted!')
	cnxn.commit()
	time.sleep(10)

### Issue
cursor.execute or cnxn.commit will not throw an error because internet is lost.

To replicate this issue: Run the script normally, after you see 'Successfuly Inserted!', switch off your internet. Now the script will hang and not throw an error.

Take a look at the picture. As you can see, the last insert is at 5:56:19 and the current system time is 5:59AM with the internet off.
http://imgur.com/ipNi2bK

**Comment by keitherskine** [comment]
1) What is the structure of the dbo.temperature table?  (In particular the `id` column).  If possible, please provide the table's CREATE sql.
2) What SQL did you run to get a list of those nine rows?  Did it have an ORDER BY clause on it?

**Comment by BChip** [comment]
@keitherskine 
1. I cannot provide a CREATE statement. However, all I did was go into Microsoft SQL Server Management Studio, right click on Tables, clicked New Table, and set the Column names and Date Types, made sure nulls are not allowed, and saved it.
2. SELECT * FROM [dbo].[temperature]

**Comment by keitherskine** [comment]
So, if you run `SELECT * FROM [dbo].[temperature] ORDER BY [recorded]`, what do you get?

In SQL, unless you specify an ORDER BY clause, the records you get back from the database can be provided in any order, and that order can be different each time you retrieve even the same records.  If you want the records in a specific order, you have to indicate that within the ORDER BY clause.

**Comment by BChip** [comment]
I get the expected output with SELECT * FROM [dbo].[temperature] ORDER BY [recorded]
Thank you.

So the issue is: When I disconnect from the internet, I do not get an error, it just hangs

**Comment by mkleehammer** [comment]
The problem here is the driver is using TCP/IP which pyodbc has nothing to do with.  pyodbc gives the SQL to [the driver / DM](https://github.com/mkleehammer/pyodbc/wiki/Drivers-and-Driver-Managers) and the driver takes over - pyodbc doesn't even know if TCP/IP is being used, named pipes, etc.

There is a [Connection.timeout](https://github.com/mkleehammer/pyodbc/wiki/Connection#timeout) you can set to force a failure when nothing comes back.  It's exactly what you want but you need to come up with a time that is not too long, but is longer than any query you are going to make.  Since it is per-connection, you can manually increase it when you know you have a long-running query.

There is a *separate* timer for making connections which is a parameter of the [connect function](https://github.com/mkleehammer/pyodbc/wiki/Module#connect).

**Comment by georgiana-bud** [comment]
I encountered the same problem when using Python 3.9.10 with pyodbc 4.0.32 on Ubuntu 18.04. Setting Connection.timeout does not work, as it throws an exception: 
pyodbc.Error: ('HY000', "[HY000] Couldn't set unsupported connect attribute 113 (216) (SQLSetConnectAttr)")

I can access the attribute, which is 0, but I cannot change its value. Was there a change in the behaviour of this attribute across pyodbc versions?

**Comment by v-chojas** [comment]
Post an ODBC trace if you'd like more detailed troubleshooting.
