### ISSUE TITLE
select into temporary table does not work with parameters

### ISSUE THREAD

**Issue by bjquast** [mkleehammer/pyodbc#263]
### Environment

- Python: 3.5.2
- pyodbc: 4.0.17
- OS: Ubuntu 16.04
- DB: MS-SQL 2014 
- driver: FreeTDS

### Issue

creating a temporary table from select works when no parameters are used in execute() method. With placeholder and parameter the execution fails silently:

`>>>  temptablequery = 'SELECT * INTO #temptable FROM [Specimen] WHERE [AccessionNumber] = ?'`
 `>>>  cur.execute(temptablequery, 'c1')`
`<pyodbc.Cursor object at 0x7f3626c1c510>`
`>>> con.commit()`
`>>>  squery = ('SELECT * FROM #temptable')`
`>>> cur.execute(squery)`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42S02', "[42S02] [FreeTDS][SQL Server]Invalid object name '#temptable'. (208) (SQLExecDirectW)")`

The same thing does work when I either use a global temporary table (`##temptable`) or replace the placeholder with a value and do not use `execute()` with parameter.

**Comment by mkleehammer** [comment]
@v-chojas Can I get your opinion on this?  Is this because the SQL Server driver wraps parameterized SQL statements with a stored procedure?  That's one of the things I wanted to eventually discuss with you & Luis - it messes up "@identity" also.  It would be great if the SQL Server team could undo that eventually.

**Comment by v-chojas** [comment]
I can't speak for FreeTDS, but with Microsoft ODBC Driver for SQL Server, queries with parameters will be executed using one of the system stored procedures, and since stored procedures are executed in a separate scope, temporary tables created there won't be accessible from outside that scope. Instead, you can try creating the table in the outer scope first:

```
 >>> cur.execute('SELECT * INTO #temptable FROM [Specimen] WHERE 0 = 1' ) # create empty table with appropriate schema
 >>> temptablequery = 'INSERT INTO #temptable SELECT * FROM [Specimen] WHERE [AccessionNumber] = ?' 
 >>> cur.execute(temptablequery, 'c1') 
 >>> con.commit() 
 >>> squery = ('SELECT * FROM #temptable') 
 >>> cur.execute(squery) 
```

**Comment by bjquast** [comment]
Thank you for looking at this. Obviously, it is the same with FreeTDS. The proposed way to create the temporary table first and then 'insert from select' works. Now I am wondering why the second query with parameter can access the scope of the temporary table even though it is executed in its own scope, but this is only a matter of my limited understanding.

**Comment by v-chojas** [comment]
That is because the query finds the table in the outer scope (i.e. the session), where it was previously created.

**Comment by bjquast** [comment]
I closed the issue as it is not a pyodbc issue.
