### ISSUE TITLE
Consolidate Parameter Code

### ISSUE THREAD

**Issue by mkleehammer** [mkleehammer/pyodbc#268]
The new array handling code duplicates a lot of the original code.  There are already differences in Unicode handling and there will be more maintenance difficulties if this is not done soon.

Design constraints:
- Unicode should use encodings
- Bytes should use encodings
- Many drivers do not support BIGINT, so only use when necessary
- Some drivers like Oracle do not encode NUMERIC correctly (needs retesting)
- IsInstanceForThread increments class counts which are not decremented (not fatal, but very bad practice)
- If executed in batches (due to type changes from set to set), make sure we get all rowcounts, not just the last batch.
- Use column description when possible since SQL Server caches a different execution plan for every column size.  (So ColumnSize does not need to match the data size?)

**Comment by mkleehammer** [comment]
Started branch 268-consolidate-parameter-code with a PostgreSQL test showing the Unicode error: test_parameter_array_strings

**Comment by v-chojas** [comment]
I think the whole situation around character encoding needs to be re-examined in detail, especially around what drivers and the driver manager use. For example, I noticed before in setup.py that it was compiling pyODBC with SQL_WCHART_CONVERT , which changes the definition of SQLWCHAR in the header files but will cause problems if the unixODBC itself wasn't compiled in that mode (since the default for SQLWCHAR is 2 bytes/UTF-16.) I will investigate this some more.

**Comment by mkleehammer** [comment]
Agreed, but be prepared for unpleasant surprises.  Even on 32-bit builds, unixODBC uses 16-bit characters for some things.  The whole thing is a mess, but it is not going away.  Also, using UTF-8, which did not exist when ODBC was defined, is probably going to be more common.

**Comment by v-chojas** [comment]
Note that although I have been very busy with other things recently, I have some time now and am still working on the refactoring of the parameter implementation which we discussed before.

**Comment by v-chojas** [comment]
I have created a PR for this here: https://github.com/mkleehammer/pyodbc/pull/301
