### ISSUE TITLE
Add support for setting transaction isolation level via ODBC (not driver-dependent)

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#270]
#135 describes how we can control the transaction isolation level for a SQL Server connection by sending a T-SQL statement like

```python
conn.execute("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;")
```

after the connection is established. However, it might be nice to support this at the ODBC level using a pyodbc method something like

```python
conn.transaction_isolation = "SERIALIZABLE"
```

Such support at the ODBC level is actually what happens when a .NET application sets the isolation level for an OdbcTransaction. The C# statement

```csharp
OdbcTransaction tran = conn.BeginTransaction(System.Data.IsolationLevel.Serializable);
```

produces the following in the ODBC trace:

```
OdbcConsoleApp. 227c-20cc   ENTER SQLSetConnectAttrW 
        SQLHDBC             0x000263F0
        SQLINTEGER                 108 <SQL_ATTR_TXN_ISOLATION>
        SQLPOINTER                 8 <SQL_TXN_SERIALIZABLE>
        SQLINTEGER                  -6 

OdbcConsoleApp. 227c-20cc   EXIT  SQLSetConnectAttrW  with return code 0 (SQL_SUCCESS)
        SQLHDBC             0x000263F0
        SQLINTEGER                 108 <SQL_ATTR_TXN_ISOLATION>
        SQLPOINTER                 8 <SQL_TXN_SERIALIZABLE>
        SQLINTEGER                  -6
```

**Comment by v-chojas** [comment]
I agree it would be a good idea to have this accessible from pyODBC; and ODBC already defines the constants needed:

- `SQL_TXN_READ_UNCOMMITTED`
- `SQL_TXN_READ_COMMITTED`
- `SQL_TXN_REPEATABLE_READ`
- `SQL_TXN_SERIALIZABLE`

However, given that this is only one of many other options accessible via connection attributes, perhaps it would be sufficient to add the constants and use `set_attr()` for this instead of adding a dedicated field, e.g.:

```
conn.set_attr(pyodbc.SQL_ATTR_TXN_ISOLATION, pyodbc.SQL_TXN_SERIALIZABLE);
```

I think it makes sense to add such a "convenience method/field" when it's part of DB-API or otherwise likely to be commonly used, but otherwise setting the isolation level is already available via `set_attr()`. Many ODBC drivers with extended functionality, like the SQL Server Native Client/ODBC Driver for SQL Server, expose that functionality through custom connection and/or statement attributes. @mkleehammer what are your thoughts on adding specific methods/fields vs. using the more generic connection/statement attribute interfaces?

**Comment by mkleehammer** [comment]
@v-chojas has added the constants to #286 which has now been merged in.

Thanks to both of you for the suggestion and implementation.
