### ISSUE TITLE
pyodbc for AWS lambda

### ISSUE THREAD

**Issue by macadminrohit** [mkleehammer/pyodbc#275]
How do i download pyodbc when i want to run the code using AWS lambda, i have tried most of the ways but for some reason pyodbc doesnt install successfully on my RHEL machine.

**Comment by gordthompson** [comment]
Is this a continuation of issue #254 ?

**Comment by macadminrohit** [comment]
No i have been able to install pyodbc , wanted to know if this can be used in AWS lamda functions rather than running the solution on a server.

**Comment by mkleehammer** [comment]
I haven't tried this myself.

It may be possible to build pyodbc into a binary wheel on an identical system and install from that wheel file.

I'm going to close for now because this seems environmental, but reopen if you have any particular error messages or something you need help with.  Good luck.

**Comment by mfulton26** [comment]
@gordthompson Did you ever get pyodbc working in an AWS Lambda?
