### ISSUE TITLE
cursor.columns(table='table中文') not work when table name has chinese

### ISSUE THREAD

**Issue by kingsonchan** [mkleehammer/pyodbc#284]
### Environment

- Python: 3.5
- pyodbc: newest at 2017-09-14
- OS: Win 7 Entprs 64-bit:
- DB: mssql
- driver:{SQL Server Native Client 11.0}

### Issue

When table name has chinese, 
cursor.columns(table='table中文')
not work. But,
for col in cursor.columns():
        if(col.table_name == 'table中文'):
              print (col)
It works.
That's why?

**Comment by v-chojas** [comment]
cursor.columns() uses the ODBC SQLColumns() function, which takes narrow (ANSI) string arguments in the current locale's encoding. Since SQLNCLI/MSODBCSQL are Unicode drivers, the driver manager will convert from ANSI to Unicode (UTF-16) and then call SQLColumnsW of the driver with the wide strings.

When you pass a (Unicode) Python string to columns(), it gets converted into a narrow string *using UTF-8*, which the DM will then attempt to interpret according to current ANSI encoding (not UTF-8) when converting to UTF-16.

'table中文' in UTF-8 is 74 61 62 6c 65 e4 b8 ad e6 96 87 , which when interpreted as e.g. '1252 ('tableä¸­æ–‡')and converted to UTF-16 becomes 74 00 61 00 62 00 6c 00 65 00 **e4 00 b8 00 ad 00 e6 00 13 20 21 20** ,
but should actually be 74 00 61 00 62 00 6c 00 65 00 **2d 4e 87 65**. Thus SQLColumnsW in the driver gets called with the UTF-16 of 'tableä¸­æ–‡' instead of 'table中文' and can't find the table.

If you don't pass any argument to columns(), then the resultset containing all the columns gets retrieved correctly as UTF-16 and the comparison is done in Python between two Unicode strings, hence why it works.

The fix is to use SQLColumnsW in pyODBC directly, so pyODBC will convert to the driver's Unicode encoding (UTF-16 for the Microsoft driver) from a Python Unicode string. I can try to work on this.

Also, the latest ODBC driver available for SQL Server is [ODBC Driver 13.1 for SQL Server](https://www.microsoft.com/en-us/download/details.aspx?id=53339)

**Comment by mkleehammer** [comment]
I've checked in a fix for this on branch 284-cursor-columns.  I've tested it on PostgreSQL on macOS.  I still need to test on MySQL macOS, PostgreSQL Linux, and Windows SQL Server.

**Comment by kingsonchan** [comment]
Thanks very much. Let's get better and better
