### ISSUE TITLE
Pyodbc connection string error

### ISSUE THREAD

**Issue by priyanka22kar** [mkleehammer/pyodbc#323]
When I write this command:
`driver = "SQL Server"
server = "server_name"
database = "my_db"
username = "sa"
password = ""
print ("'DRIVER={" + str (driver) + "};SERVER=" + str (server) + ";DATABASE=" + str (database) + ";UID=" + str (
    username) + ";PWD=" + str (password) + "'")

import pyodbc

conn = pyodbc.connect ('DRIVER={SQL Server};SERVER=server_name;DATABASE=my_db;UID=sa;PWD=')

getcon = conn.cursor ()
print ("Connected to Database!")
`

the database gets connected .
but when i fetch the credentials from user via tkinter entry widget 
and try to execute it it gives me errro:
('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
I thought that maybe variable is not fetching values from textbox
but i checked and found that values are fetched to the variables into the text box 
What can be the issue 
Please help!

**Comment by boumboum** [comment]
Try this:
 connstr = (
        r'Driver=ODBC Driver 13 for SQL Server;'
        r'Server=myserver,1433;'
        r'Database=mydb;'
        r'UID=user;'
        r'PWD=pass;'
        r'MARS_Connection=yes;'
        r'APP=yourapp'
    )
db = pyodbc.connect(connstr)

Where the Driver is one of your driver installed on your system

**Comment by priyanka22kar** [comment]
@boumboum Sir 
I am fetching the driver , server, database, username,password from UI tkinter 
that is when it is causing me problem.

**Comment by boumboum** [comment]
Then just replace the values of your result in the connection string:
    connstr = (
        r'Driver=' + driver +';'
        r'Server=' + server + ';'
        r'Database=' + database + ';'
        r'UID=' + username + ';'
        r'PWD=' + password + ';'
        r'MARS_Connection=yes;'
        r'APP=yourapp'
    )
db = pyodbc.connect(connstr)
cr = db.cursor()
For me it's working

**Comment by priyanka22kar** [comment]
Sir
r'MARS_Connection=yes;'
r'APP=yourapp'
what does this parameter consist of?

**Comment by boumboum** [comment]
Hi,

MARS_Connection = Using Multiple Active Result Sets
[](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars)
I use it as default behavior because in the past I've got problems and that solved is
the APP parameter is useful if you want to differentiate  your app within the process list.
I usually have several hundreds of connection and it is easier to identify some specific processes if there is any distinctions mark. But you can omit it.

Otherwise you have a problem, because you have a string within the string.
So instead of this
conn = pyodbc.connect ("'DRIVER={" + str (d) + "};SERVER=" + str (s) + ";DATABASE=" + str (db) + ";UID=" + str (uid) + ";PWD=" + str (pwd) + "'")

you should use his:
conn = pyodbc.connect ("DRIVER={" + str (d) + "};SERVER=" + str (s) + ";DATABASE=" + str (db) + ";UID=" + str (uid) + ";PWD=" + str (pwd))

**Comment by v-chojas** [comment]
You should ensure that any special characters are correctly escaped (in particular, the password --- which _should_ contain special characters for good security.) As it is, your code will fail if any of those values contain `;` characters. For more information on connection string syntax, please see https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client

**Comment by mkleehammer** [comment]
@priyanka22kar Did this answer your question?  Can I close this now?
