### ISSUE TITLE
pyodbc connection pool

### ISSUE THREAD

**Issue by AnkitaSambhare** [mkleehammer/pyodbc#330]
Hello,

I am trying to use pyodbc to connect to a sql server from a linux machine to execute some stored procedure. I realized setting the pooling = Yes for the driver is a great way to maintain a pool of connections open if one needs to create and close a connection pretty often. However, I couldn't find a way to test that connection pool is actually enabled.  Can you please help me with this?

Thanks,
Ankita

**Comment by v-chojas** [comment]
Try `SELECT @@SPID` from different "connections", and if pooling is enabled it will not change since it is actually reusing the same connection.

Note that due to limitations/bugs in unixODBC, you will need unixODBC 2.3.5 or newer and `ansi=True` in your `connect()` to enable pooling. [https://github.com/mkleehammer/pyodbc/issues/283](See here for more information and discussion.)
