### ISSUE TITLE
Distributed transaction in pyodbc

### ISSUE THREAD

**Issue by sidnaik03** [mkleehammer/pyodbc#354]
How to perform distributed transaction using pyodbc. Is there any provision for that ?

**Comment by v-chojas** [comment]
Please provide more information about your environment (OS, DBMS, driver, etc.)

**Comment by gordthompson** [comment]
This is also being discussed on Stack Overflow [here](https://stackoverflow.com/q/48944129/2144390).

**Comment by sidnaik03** [comment]
I want to perform distributed transaction using pyodbc for MSSQL.  I am using sql alchemy core to perform the same. I am using mssql + pyodbc dialect . When I am trying to perform begin_twophase() operation its throws error 'Not ImplementedError' .More details [here](https://bitbucket.org/zzzeek/sqlalchemy/issues/4173/begin_twophase-method-throws-error-as-not)

**Comment by mkleehammer** [comment]
If I am reading this correctly, the function is disabled in SQLAlchemy because it never worked correctly with SQL Server.  Therefore I'm going to close this.  If there is something specific that could be added to pyodbc to help with this, or if I misread [SQLAlchemy issue 4173](https://bitbucket.org/zzzeek/sqlalchemy/issues/4173/begin_twophase-method-throws-error-as-not), feel free to reopen.  Thanks.
