### ISSUE TITLE
Cursor throws an error when trying to insert in SQL Server database when fast_executemany flag is set

### ISSUE THREAD

**Issue by manrajgrover** [mkleehammer/pyodbc#371]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.14
- pyodbc: 4.0.23
- OS: MacOS
- DB: SQL Server
- driver: ODBC Driver 13 for SQL Server

### Issue

Trying to use fast execute many option to insert data to the database throws the error shown below. It works if the flag is not set.

#### Expected behavior:

Cursor should be able to write to database without throwing an error.

#### Observed behavior:

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-24-5e5f851229b4> in <module>()
      1 cursor.fast_executemany = True
----> 2 cursor.executemany(query, x.values.tolist())

Error: ('HY010', u'[HY010] [unixODBC][Driver Manager]Function sequence error (0) (SQLParamData)')
```

**Comment by gizmo93** [comment]
The same here:

Python: 3.5.5
pyodbc: 4.0.23
OS: Windows 10
DB: SQL Server 2017 and 2016
driver: ODBC Driver 13 for SQL Server

tried with SQL Server Native Client too. 

Could not determine, where the problem is, but it seems to have to do with string data.

Installed 4.0.22 again and the problems are not there anymore.

**Comment by v-chojas** [comment]
Could you post a example table schema + Python code to reproduce it, and/or ODBC trace log? That will help with the troubleshooting.

**Comment by gizmo93** [comment]
Hey @v-chojas 

It was happening while trying to insert a pandas dataframe with to_sql.

[b64.txt](https://github.com/mkleehammer/pyodbc/files/1922894/b64.txt)

Thats the dataframe, pickled and base64 encoded.
You can use decoded = pickle.loads(base64.b64decode(encoded)) to turn it back into a dataframe and then you can just use encoded.to_sql() to reproduce the error. (Pandas will create a table itself, it it does not exist).

Error Message: Function sequence error (0) (SQLParamData)

**Comment by gordthompson** [comment]
Reproduced with pyodbc 4.0.23 under 64-bit Python 3.6.4 on Windows 7 with SQLAlchemy 1.2.6. Also confirmed that it is specific to 4.0.23 (4.0.22 works) and is related to string parameter values.

With pyodbc 4.0.23 this works:

```python
import pandas as pd
from sqlalchemy import create_engine, event
cnxn_url = 'mssql+pyodbc://@SQLmyDb'
engine = create_engine(cnxn_url)


@event.listens_for(engine, 'before_cursor_execute')
def receive_before_cursor_execute(conn, cursor, statement, params, context, executemany):
    if executemany:
        cursor.fast_executemany = True

        
table_name = 'fast_executemany_test'
df = pd.DataFrame({'col1':[1, 2]})
df.to_sql(table_name, engine, if_exists = 'replace', chunksize = None)
```

ODBC trace: 
[numeric_ok_log.zip](https://github.com/mkleehammer/pyodbc/files/1924630/numeric_ok_log.zip)

However, if I change the dataframe to contain strings instead of numbers

```python
df = pd.DataFrame({'col1':['foo', 'bar']})
```

then I get

> sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [Microsoft][ODBC Driver 11 for SQL Server]Function sequence error (0) (SQLParamData)') [SQL: 'INSERT INTO fast_executemany_test ([index], col1) VALUES (?, ?)'] [parameters: ((0, 'foo'), (1, 'bar'))] (Background on this error at: http://sqlalche.me/e/dbapi)

ODBC trace:
[string_fail_log.zip](https://github.com/mkleehammer/pyodbc/files/1924633/string_fail_log.zip)

**Comment by gordthompson** [comment]
Related issues are being discussed in the Stack Overflow question [here](https://stackoverflow.com/q/49887717/2144390).

**Comment by v-chojas** [comment]
Can you create repro with only the pyODBC calls being made?

I cannot reproduce it with this:
```
import pyodbc
conn = pyodbc.connect([your connection string here], autocommit=True)
stmt = conn.cursor()
stmt.execute("DROP TABLE IF EXISTS fastexecutemany_test")
stmt.execute("CREATE TABLE fastexecutemany_test([index] BIGINT NULL, col1 VARCHAR(MAX) NULL)")
stmt.fast_executemany = True
stmt.executemany("INSERT INTO fastexecutemany_test([index], col1) VALUES(?, ?)", [[1,'foo'],[2,'bar']])
print stmt.execute("SELECT * from fastexecutemany_test").fetchall()
```

**Comment by gordthompson** [comment]
@v-chojas - Before posting I tried to reproduce the issue with plain pyodbc but could not. That's why I went with the pandas code and the ODBC logs in case they gave a hint as to what pandas (or perhaps SQLAlchemy) was doing differently.

**Comment by gordthompson** [comment]
Also worth noting that this appears to be related to Python_3. I just tried my repro code under Python 2.7.14 and using

```python
df = pd.DataFrame({'col1':['foo', 'bar']})
```

worked without complaint.

**Comment by billmccord** [comment]
I believe that, at least in my case, the issue is caused by passing an empty string as a param to execute many. I have reproduced it with very simple code (DSN, UID and PWD excluded):
```
import pyodbc

cnxn = pyodbc.connect(
    'DSN={};UID={};PWD={}'.format(
        DATABASE_DSN,
        DATABASE_USERNAME,
        DATABASE_PASSWORD,
    ))

# Create a cursor from the connection
cursor = cnxn.cursor()

cursor.execute('BEGIN TRY DROP TABLE [test] END TRY BEGIN CATCH END CATCH')

cursor.execute('CREATE TABLE [test]([testcol] [nvarchar](MAX) NULL)')

cursor.fast_executemany = True
cursor.executemany('INSERT INTO [test] VALUES(?)', [['']])

cursor.commit()
```

For me, this fails using ODBC Driver 17 for SQL Server on Mac and Windows and on Python 2 and 3. There are a number of ways to make this code work:
- Disable fast_executemany
- Change empty string '' to None
- Change empty string '' to a non-empty string

I also added a trace as per this [issue](https://github.com/mkleehammer/pyodbc/issues/396#issuecomment-392824392), but it didn't seem to be particularly revealing:
```
[ODBC][7255][1527828468.407527][__handles.c][460]
		Exit:[SQL_SUCCESS]
			Environment = 0x7fbec2829000
[ODBC][7255][1527828468.407719][SQLSetEnvAttr.c][189]
		Entry:
			Environment = 0x7fbec2829000
			Attribute = SQL_ATTR_ODBC_VERSION
			Value = 0x3
			StrLen = 4
[ODBC][7255][1527828468.407890][SQLSetEnvAttr.c][381]
		Exit:[SQL_SUCCESS]
[ODBC][7255][1527828468.407998][SQLAllocHandle.c][377]
		Entry:
			Handle Type = 2
			Input Handle = 0x7fbec2829000
[ODBC][7255][1527828468.408150][SQLAllocHandle.c][493]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x7fbec3810000
[ODBC][7255][1527828468.408722][SQLDriverConnectW.c][290]
		Entry:
			Connection = 0x7fbec3810000
			Window Hdl = 0x0
			Str In = [DSN=xxx;UID=xxx;PWD=xxx][length = 53]
			Str Out = 0x0
			Str Out Max = 0
			Str Out Ptr = 0x0
			Completion = 0
		UNICODE Using encoding ASCII 'US-ASCII' and UNICODE 'UCS-2-INTERNAL'

[ODBC][7255][1527828469.087117][__handles.c][460]
		Exit:[SQL_SUCCESS]
			Environment = 0x7fbec2801800
[ODBC][7255][1527828469.087380][SQLGetEnvAttr.c][157]
		Entry:
			Environment = 0x7fbec2801800
			Attribute = 65002
			Value = 0x7ffee0d200c0
			Buffer Len = 128
			StrLen = 0x7ffee0d200a4
[ODBC][7255][1527828469.087941][SQLGetEnvAttr.c][273]
		Exit:[SQL_SUCCESS]
[ODBC][7255][1527828469.088077][SQLFreeHandle.c][220]
		Entry:
			Handle Type = 1
			Input Handle = 0x7fbec2801800
```

For now, I can workaround by ensuring that I always use None instead of '', but would appreciate it if someone knows of other workarounds.

**Comment by tigerhawkvok** [comment]
Ran into this, and replacing empty strings with `" "` doesn't work, either. Pandas was throwing errors trying `dbPushable.replace('', None, inplace= True)`, so I didn't test that.

Running

- Python 3.6
- pyodbc 4.0.23
- Pandas 0.23.0
- ODBC Driver 17 for SQL Server
- Windows 10


Full error:

```
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1534, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py", line 473, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1156, in to_sql
    table.insert(chunksize)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py", line 670, in insert
    self._execute_insert(conn, keys, chunk_iter)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py", line 645, in _execute_insert
    conn.execute(self.insert_statement(), data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1170, in _execute_context
    context)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 504, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLParamData)')
```

**Comment by v-chojas** [comment]
Please provide an ODBC trace; if you are using Linux/Mac, upgrade to unixODBC 2.3.7pre (available here on GitHub: https://github.com/lurcher/unixODBC/ ) if you are using ODBC Driver 17 since it fixes a logging bug, and otherwise the trace will not contain any useful information.

**Comment by veeology** [comment]
Not sure if this will help anyone else, but in my case in my case the issue turned out to be related to some kind of character encoding issue.  Using the code provided by v-chojas earlier in the thread, I am able to reproduce the error with this:

`conn = pyodbc.connect([your connection string here], autocommit=True)
stmt = conn.cursor()
stmt.execute("DROP TABLE IF EXISTS fastexecutemany_test")
stmt.execute("CREATE TABLE fastexecutemany_test([index] BIGINT NULL, col1 VARCHAR(MAX) NULL)")
stmt.fast_executemany = True
stmt.executemany("INSERT INTO fastexecutemany_test([index], col1) VALUES(?, ?)", [[1,'foo'],[2,'bar']])
print stmt.execute("SELECT * from fastexecutemany_test").fetchall()`

Result:
`Error: ('HY010', '[HY010] [Microsoft][ODBC Driver 13 for SQL Server]Function sequence error (0) (SQLParamData)')`

But explicitly encoding the string data as ascii allowed the code to execute correctly.  This is the code I used:
`stmt.executemany("INSERT INTO fastexecutemany_test([index], col1) VALUES(?, ?)", [[1,'foo'.encode('ascii')],[2,'bar'.encode('ascii')]])
print (stmt.execute("SELECT * from fastexecutemany_test").fetchall())`

Result:
`[(1, 'foo'), (2, 'bar')]`

Environment: Python 3.6, pyodbc 4.0.23, connecting to an Azure-SQL database

**Comment by logicalextreme** [comment]
I can also confirm that this affects pyodbc 4.0.23 but not 4.0.22.

Explicitly encoding the string value as @veeology mentioned works for me, though I also need to change empty strings to `None` as @billmccord said — not really viable if you're hoping to preserve the distinction between empty strings and NULLs (I'm pushing data from a pyodbc MySQL cursor to a pyodbc SQL Server cursor).

However I've made two further observations:

- this only happens to columns declared with the `varchar(max)` and `nvarchar(max)` data types; you can confirm this by changing your `(max)` column length to 8000 or 4000 (or less) respectively
- HY010 doesn't happen if the _params_ value is a generator object, but definitely happens if it's a sequence; however I believe that fast_executemany behaviour doesn't occur with a generator/non-sequence as performance completely tanks when attempting to do so

My guess then is that 4.0.23 is no longer automatically preparing parameter values as binary for `(max)` columns during fast_executemany operations. This would be explained by my two observations here and @veeology's workaround, though the empty string thing confuses me.

I'm personally reverting to 4.0.22 as I have to write a fair bit of extra code to work around this and it incurs a performance penalty of about 25%. However if anybody does use @veeology's workaround for 4.0.23, I think you'll be wanting to encode in `utf_16_le` for `nvarchar(max)` columns and you're probably safest (codepage-wise) with `utf8` for `varchar(max)`, based on the docs [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/programming-guidelines?view=sql-server-2017#character-set-support).

My setup:

Win10
ODBC Driver 17 for SQL Server (64-bit)
Python 3.6.5 and 3.7.0, both Windows 64-bit

**Comment by v-chojas** [comment]
Thanks for the trace. It appears that pyODBC is calling SQLParamData twice without ever actually sending the data for the parameter with SQLPutData. I will investigate this.

**Comment by v-chojas** [comment]
I have determined that it is caused by small bug in the code, which is not sending 0-length parameters. Try the fix here: https://github.com/mkleehammer/pyodbc/pull/425

**Comment by billmccord** [comment]
OK, I had rolled back to 4.0.22 in order to resolve this issue, but it looks like when I run with 4.0.22 something goes screwy when I insert data. When I retrieve the inserted data, it has a bunch of '\x00' characters in between the characters of a bunch of varchars in the database. It's really weird and doesn't happen with version 4.0.23.

Any chance you can make another release with the #425 fix?

**Comment by billmccord** [comment]
Not intentionally, but I'm not specifying an encoding anywhere. The database is the default encoding. I ran a test where I insert data and retrieve and compare. Run with 4.0.22 the test has the weird characters. Run with 4.0.23 it doesn't.

**Comment by v-chojas** [comment]
> Any chance you can make another release with the #425#425, Fix DAE for 0-length parameters fix?

@mkleehammer

**Comment by billmccord** [comment]
Never mind, I see that it is in a different repo, sorry about that. I'll try there.

**Comment by billmccord** [comment]
Alright, I finally got the pull request that @v-chojas sent to build on Windows. Originally, I had observed that when I ran my [test program](https://github.com/mkleehammer/pyodbc/issues/371#issuecomment-393757030) on my Mac it was working. However, I just tried it on Windows after doing a manual build and I still get the following error when trying to executemany and it doesn't matter if I use an empty string or a single space:
`pyodbc.Error: ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLParamData)')`

It seems the problem is still not fixed on Windows. Please find the ODBC log attached.

[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/2227053/SQL.LOG)

**Comment by tigerhawkvok** [comment]
I **think** it looks like the \x00 issue @billmccord  might be this line here, based on what you say in #432 :

- https://github.com/mkleehammer/pyodbc/compare/mkleehammer:4.0.22...4.0.23?diff=split#diff-fbf1bf624bc2998181a17b14c550af0dL363
- https://github.com/mkleehammer/pyodbc/compare/mkleehammer:4.0.22...4.0.23?diff=split#diff-fbf1bf624bc2998181a17b14c550af0dL709

They both can raise error 0 and also output the text about right truncation, which all seems to be tied together.

No matter what, I'm pretty sure the issue lives in [`src/params.cpp`](https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp)

I know just enough C to be dangerous, and if anyone wants they can try a tentative patch I put here:

https://github.com/tigerhawkvok/pyodbc/commit/01ad3d83e5a9d84ddf85d20eb7b5c753ca117945

It's also possible the issue is, based on [this diff](https://github.com/mkleehammer/pyodbc/compare/mkleehammer:4.0.22...4.0.23), that the problem originates in changing [the `do-while` code](https://github.com/mkleehammer/pyodbc/compare/mkleehammer:4.0.22...4.0.23#diff-33349116f9098ad7bbcddbcafce69b0cL592) into a straight-up [`while` block](https://github.com/mkleehammer/pyodbc/compare/mkleehammer:4.0.22...4.0.23#diff-33349116f9098ad7bbcddbcafce69b0cR693). But I don't think that's as likely.

**Comment by v-chojas** [comment]
Please try recently released pyODBC 4.0.24.

**Comment by tigerhawkvok** [comment]
Still no dice on 4.0.24.

I see [the comment on #450](https://github.com/mkleehammer/pyodbc/issues/450#issuecomment-415791597), any chance this will see a release soon?

**Comment by akhanna38** [comment]
Can someone provide a workaround for this issue? I tried using old versions and changing driver but no success. it gives different errors.

**Comment by billmccord** [comment]
@akhanna38 If you're at the beginning of a project, my recommendation would be to run away from using Python to communicate with SQL Server and use C# or something that runs natively on Windows and doesn't use ODBC. If you have to use Python, use 4.0.22, perform manual encoding as per #432 and follow my workarounds there:
https://github.com/mkleehammer/pyodbc/issues/432#issuecomment-408034383

**Comment by gordthompson** [comment]
I can confirm that PR #467 fixes the issue I had with SQLAlchemy, pandas, and fast_executemany documented in my [earlier comment](https://github.com/mkleehammer/pyodbc/issues/371#issuecomment-382420742) of this thread.

**Comment by smmurphy** [comment]
I can second @gordthompson 's confirmation. I found this series of threads around the same issue and installing from PR #467 fixed the issue for me on Windows 7.

**Comment by maki-markie** [comment]
Hi Everyone! 
Any news, fixes or work-arounds about this problem? I got this error message just yesterday 15.10.2018 trying to extract from a cache db source.
Thanks

**Comment by v-chojas** [comment]
Please try PR #467

**Comment by maki-markie** [comment]
still not working my requirements:
Package         Version
--------------- ------
python 3.7.0
numpy           1.14.5
pandas          0.23.3
pip             18.1  
pyodbc          4.0.24
python-dateutil 2.7.3 
pytz            2018.5
setuptools      39.0.1
six             1.11.0
SQLAlchemy      1.2.10

**Comment by gordthompson** [comment]
@maki-markie - Did you install from the code on GitHub? Your list says pyodbc 4.0.24, which does not include the fix in #467.

**Comment by maki-markie** [comment]
still having some trouble after installing the : pyodbc 4.0.0-unsupported
pyodbc.Error: ('HY000', '[HY000] [Cache ODBC][State : HY000][Native Code 400]\r\n..\\venv\\Scripts\\python.exe]\r\n[SQLCODE: <-400>:<Fatal error occurred>]\r\n[Cache Error: <<VALUE OUT OF RANGE>%0AmBs1+1^%sqlcq.SPEDITION.cls136.1>]\r\n[Location: <ServerLoop - Query Fetch>]\r\n[%msg: <Unexpected error occurred:  <VALUE OUT OF RANGE>%0AmBs1+1^%sqlcq.SPEDITION.cls136.1>] (400) (SQLGetData)')

**Comment by v-chojas** [comment]
@maki-markie What ODBC driver are you using? That message does not look familiar.

**Comment by gordthompson** [comment]
@maki-markie - Are you working with a [Caché](https://en.m.wikipedia.org/wiki/InterSystems_Caché) database?

**Comment by maki-markie** [comment]
@gordthompson hi, sorry for the late reply. yes i am working with cache database. do you have any experience with this? thanks

**Comment by MrMathias** [comment]
@gordthompson #467 seems to relate more to null values than empty string values. I am testing it now.

Best workaround so far seems to be to replace empty strings with null or whitespace.

**Comment by gordthompson** [comment]
@logicalextreme re: "I believe that fast_executemany behaviour doesn't occur with a generator/non-sequence"

That does seem to be the case. Details in issue #500

**Comment by mkleehammer** [comment]
Did that answer the question?  Should we close this and pursue #500?

**Comment by gordthompson** [comment]
Yes, I'd say that this can be closed. #467 addressed the main issue; the mention of #500 was just a tangent resulting from an [earlier comment](https://github.com/mkleehammer/pyodbc/issues/371#issuecomment-402041076).

**Comment by eddyizm** [comment]
I've been watching this thread for several months and still not able to use the fast execute. 
I am on the latest version . Do I need any other packages updated?  I'm googling for a work around but I'm wary of having to maintain those going forward. 

Name: pyodbc
Version: 4.0.25

`(pyodbc.Error) ('HY090', '[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length (0) (SQLBindParameter)')`

**Comment by eddyizm** [comment]
@maki-markie Check your sql driver once you get the latest pyodbc. I would bet that is where the issue lies.

**Comment by v-chojas** [comment]
@eddyizm he is not using SQL Server, but I would not be surprised if the ODBC driver does not support parameter arrays; fast_executemany was originally designed for and works best with ODBC Driver 17 for SQL Server, although it may also be usable with other drivers.

**Comment by Puneeth2** [comment]
I am Trying to insert the data from CSV file to SQL server dynamically using python below is the code
with open (FILENAME, 'r') as f:
	#reader = csv.reader(f)
	reader = csv.reader(f, delimiter=',',lineterminator='\r\n', quoting=csv.QUOTE_NONNUMERIC) 
	data = next(reader) 
#query="Bulk INSERT " + ShortName + " From = " + infile + " with(FIELDTERMINATOR =',')"
	query="INSERT into " + ShortName + " values ({0})"
#print(query)
	query = query.format(','.join('?' * len(data)))
	cursor_Sql = cnxn.cursor()
	cursor_Sql.execute(query, data)
	for data in reader:
		cursor_Sql.execute(query, data)
		cursor_Sql.commit()

But i am getting the pyodbc.Error: ('07002', '[07002] [Microsoft][SQL Server Native Client 11.0]COUNT field incorrect or syntax error (0) (SQLExecDirectW)') error can any one please help this?

**Comment by gordthompson** [comment]
@Puneeth2 - Your question does not appear to be related to the behaviour of pyodbc itself, so you might have better luck getting an answer on [Stack Overflow](https://stackoverflow.com/questions/tagged/pyodbc).

**Comment by selvakarna** [comment]
sql server cannot find ? using python from Linux OS?

SQL Server ---in Windows OS
my application run----Linux OS?

How to solve ?sql server cannot find

**Comment by gordthompson** [comment]
@selvakarna - Your question does not appear to be related to this particular issue. Try asking for help on [Stack Overflow](https://stackoverflow.com/questions/tagged/pyodbc).

**Comment by diegoaranas** [comment]
I came across this bug recently.

Python: 3.7.3
pyodbc: 4.0.26
pandas: 0.24.2
SQLAlchemy: 1.3.5
OS: Windows 10
driver: ODBC Driver 17 for SQL Server

**Comment by nrhead** [comment]
I'm having the same issue as well. I've installed the pyodbc version in #467. My pyodbc version is 4.0.18b89.

**Comment by gordthompson** [comment]
@nrhead - Try upgrading pyodbc to version 4.0.27.

**Comment by hishamsajid** [comment]
Upgraded to version 4.0.27 and explicitly encoded the `object` type columns to `ascii`, it seems to be working now.
```
for col,dtype in tbl_df.dtypes.iteritems():
    if(dtype=='object'):
        tbl_df[col] = tbl_df[col].str.encode('ascii')
```

**Comment by ethan-deng** [comment]
Same issue with 4.0.27
Python: 3.7.3
pyodbc: 4.0.27
OS: Windows 10
driver: ODBC Driver 17 for SQL Server

**Comment by gordthompson** [comment]
@ethan-deng - Please open a [new issue](https://github.com/mkleehammer/pyodbc/issues/new) and include an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that clearly illustrates the specific problem you are currently seeing.

**Comment by ethan-deng** [comment]
The solution of https://github.com/mkleehammer/pyodbc/issues/617

and install the bug fix helps.

pip install git+https://github.com/v-makouz/pyodbc.git@bugfix_unicode_size --user

**Comment by keitherskine** [comment]
Closed due to inactivity.

**Comment by Ephafrus** [comment]
Solution is to go to the ODBC Driver created, change character format from utf-8 to ASCII. Keep changing and testing. There is server miscommunication due to character set.
