### ISSUE TITLE
varchar filtering slow with python strings

### ISSUE THREAD

**Issue by davesullivan41** [mkleehammer/pyodbc#376]
### Environment

- Python: 3.6
- pyodbc: 4.0.22
- OS: Ubuntu 16.04
- DB: MSSQL
- driver: ODBC Driver 13 for SQL Server

### Issue

I have a database with varchar values I need to filter on based off of the value of a string in python, e.g.
```cursor.execute("SELECT * FROM my_database WHERE name=?", (string_name,))``` 

When I pass in a standard python ASCII string as a parameter, the query becomes extremely slow, with an execution time of 7 seconds. However, if I encode the string as 'utf-8', the execution is reduced to tens of milliseconds, e.g.
```cursor.execute("SELECT * FROM my_database WHERE name=?", (string_name.encode('utf-8'),))``` 

I understand that it is best practice to use 'utf-8' for this sort of thing, but would it be possible to add either some sort of warning or an attempt to auto-encode queries against varchar columns as 'utf-8'?

**Comment by v-chojas** [comment]
What is the column type you're filtering on, and the length of the strings?

In Python 3.x the "standard python ASCII string" doesn't exist, it's either `bytes` or Unicode strings.

Either way, there should not be several orders of magnitude difference. You can collect and post an ODBC trace to assist in the investigation.

**Comment by gordthompson** [comment]
This sounds to me like a "varchar/nvarchar mismatch" issue. If the column in question is actually `varchar` (not `nvarchar`) and is indexed, then under Python_3

```python
sql = "SELECT * FROM tbl_txt WHERE txt_varchar=?"
params = ('foo',)
crsr.execute(sql, params)
```

will result in

```sql
exec sp_prepexec @p1 output,N'@P1 nvarchar(3)',N'SELECT * FROM tbl_txt WHERE txt_varchar=@P1',N'foo'
```

whereas

```python
sql = "SELECT * FROM tbl_txt WHERE txt_varchar=?"
params = ('foo'.encode(),)
crsr.execute(sql, params)
```

will result in

```sql
exec sp_prepexec @p1 output,N'@P1 varbinary(3)',N'SELECT * FROM tbl_txt WHERE txt_varchar=@P1',0x666F6F
```

I suspect that in the first case the query cannot use the index on `txt_varchar` because of the implicit cast to Unicode (to match the Unicode value `N'foo'` supplied as the argument), but in the second case it can use the index (conveniently ignoring code page issues).

**Comment by gordthompson** [comment]
@davesullivan41 re: "I understand that it is best practice to use 'utf-8' for this sort of thing"

Not really, because that doesn't account for the code page of the `varchar` column. Blindly encoding as 'utf-8' will only work for varchar columns using code pages that have almost complete overlap with utf-8 encoding, specifically ISO-8859-1 and, to a lesser extent, Windows "ANSI" (Windows-1252).

**Comment by davesullivan41** [comment]
@gordthompson The nvarchar vs. varchar issue makes sense to me, given the differences in encoding and the way python handles strings. It was frustrating to have the problem manifest in a dramatic increase in execution time rather than an error or warning, but I guess that sort of handling may be more appropriate in something higher level than a base odbc library. 

I'm trying to verify that that is the problem by viewing the execution plan, but I can't seem to find out how to get that from pyodbc. Can you point me to the documentation or show me the code for how to do that? I tried googling around and going through the documentation for the cursor object, but didn't find anything. 


Also, I'm basing my 'utf-8' comment on: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/programming-guidelines?view=sql-server-2017, in particular the line 'For ODBC Driver 13 and 13.1, SQLCHAR data must be UTF-8. '

I very well could be misunderstanding that, however. 

Thanks for the help!

**Comment by v-chojas** [comment]
Execution plans are a server-side thing, thus specific to the DBMS in use and not something pyODBC would handle.

For SQL Server, see

https://docs.microsoft.com/en-us/sql/relational-databases/performance/display-and-save-execution-plans
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-showplan-all-transact-sql

**Comment by gordthompson** [comment]
@davesullivan41 re: SQLCHAR and UTF-8

Thanks for the citation. It's certainly *possible* that the 13.x driver indeed prefers (requires?) SQLCHAR data encoded as UTF-8 and "passed" as `varbinary`, leaving the translation to the `varchar` code page as a task for the SQL Server instance itself. However, that would lead me to ask why essentially the same thing couldn't be done for Python_unicode parameters (whatever encoding is used, most likely UTF-16LE) "passed" as `nvarchar`, since in both cases we're supposedly passing a Unicode parameter value for a non-Unicode column. It seems that the Devil, once again, is in the Details. :smiley:

**Comment by davesullivan41** [comment]
Sorry for the delay, I got pulled into another direction for a while, but I have verified that using nvarchar instead of varchar fixed the problem. It appears that it was an issue of not being able to use the index if just a normal python string was provided. Casting as utf-8 was more of a mask of the root problem rather than a solution. 

Next time I'll pay more attention to the encoding. Thank you for your help, I'm happy to consider this closed.
