### ISSUE TITLE
Readonly is not working

### ISSUE THREAD

**Issue by rajashekarappala** [mkleehammer/pyodbc#403]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.5
- pyodbc: 4.0.23
- OS: Ubuntu 16.04
- DB: Postgresql, Mysql and MsSql
- driver: psqlodbca.so,psqlodbcw.so, libmyodbc5w.so and libmsodbcsql-17.1.so.0.1

### Issue
Adding readonly option is not working.
ex:
 `
pyodbc.connect("driver={PostgreSQL Unicode};server=localhost;database=test;uid=postgres;pwd=xxxxxxx;port=5432;readonly=True")
`
also tried 
`pyodbc.connect("driver={PostgreSQL Unicode};server=localhost;database=test;uid=postgres;pwd=xxxxxxx;port=5432;readonly=True", auto_commit=True)
`

**Comment by keitherskine** [comment]
Have you tried using the `readonly` option in the  `pyodbc.connect()` command (https://github.com/mkleehammer/pyodbc/wiki/Module#connect) ?  That is:
```python
pyodbc.connect("driver=...", readonly=True)
```

**Comment by keitherskine** [comment]
By the way, I have found that for the Vertica database, ";ReadOnly=true" within the connection string worked, but adding the `readonly=True` parameter to `pyodbc.connect()` did not work.

**Comment by rajashekarappala** [comment]
@keitherskine Thank you. 
I have tried the first one(did not work) but did not try the second will try once

**Comment by rajashekarappala** [comment]
@keitherskine Even second also not working

**Comment by v-chojas** [comment]
In Microsoft ODBC Driver for SQL Server, the correct connection string keyword is `ApplicationIntent`; thus put `ApplicationIntent=ReadOnly` in your connection string to indicate a read-only connection.

There are differences between the connection string keywords which different ODBC drivers will accept, beyond the most basic ones.

**Comment by gordthompson** [comment]
@v-chojas Just to clarify: My understanding is that `ApplicationIntent=ReadOnly` is a "hint" to SQL Server that the connection will only be used for read operations, and not a "directive" to SQL Server that write operations should be disallowed. In other words, `ApplicationIntent=ReadOnly` will not *force* a connection to be read-only. Is that correct?

**Comment by keitherskine** [comment]
I've tested this on SQL Server 2016, and `ApplicationIntent=ReadOnly` does not stop INSERT statements.

Setting `readonly=True` on the connection does stop INSERTs, but there is no exception raised when INSERT is attempted.  The INSERT just silently doesn't happen, which to be honest is somewhat concerning.

**Comment by v-chojas** [comment]
@gordthompson yes, that is correct.

In any case, pyODBC's `readonly` attribute sets the `SQL_ATTR_ACCESS_MODE` connection attribute after connecting, but according to https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function ,

"SQL_ATTR_ACCESS_MODE and SQL_ATTR_CURRENT_CATALOG can be set before or after connecting, depending on the driver. However, interoperable applications set them before connecting because some drivers do not support changing these after connecting"

More discussion here:

https://stackoverflow.com/questions/42102731/readonly-connection-with-mssql-and-pyodbc

If you must have a truly read-only connection, the most reliable way is to enforce it server-side by setting up an account with the appropriate permissions (or lack thereof) and using that.

**Comment by mkleehammer** [comment]
@gordthompson and @v-chojas explained it well.  The `readonly` keyword causes pyodbc to set the appropriate driver mode, but it is up to the driver to enforce it.  Honestly, I don't know of one that does at this point.  It might be better to remove / deprecate the keyword.
