### ISSUE TITLE
FreeTDS and SQL Server: Could Not Find Stored Procedure 'S'

### ISSUE THREAD

**Issue by mpwoodward** [mkleehammer/pyodbc#41]
Environment:
* Python 3.4
* Ubuntu Server 14.04

I can connect to SQL Server fine, but when I try to execute a simple select statement:
conn = pyodbc.connect('... connection info ...')
cursor = conn.cursor()
cursor.execute('SELECT foo FROM bar')

I get this error:
http://pastebin.com/uyfj5qCq

This seems to be the same issue described when using Python 2.x here:
https://code.google.com/p/pyodbc/issues/detail?id=110

I'm still messing with it to try and figure out the encoding issue described in that older ticket, but thought I'd bring it up here in the mean time to see if there's any additional information that would be helpful.

Thanks!

**Comment by lmagomes** [comment]
I have the same problem, but querying sybase ASE. This is also on python 3.4 but running on debian 8. I have installed the latest version of pyodbc (3.0.9) with pip.

both tsql and isql can connect with no issues to the database, and do normal select statements, but pyodbc and sqlalchemy give me the same error as above. I also tried playing around with the configurations for client encoding with no success.

This seems to be related to issue #40. I tried installing 3.0.8 with pip, which had the same problem. Since 3.0.7 doesn't seem to be available on pypi anymore I downloaded it from [google code (direct link to the file)](https://code.google.com/p/pyodbc/downloads/detail?name=pyodbc-3.0.7.zip), and installed it from there. 3.0.7 seems to work with no correctly, both on pyodbc and using sqlalchemy.

**Comment by mkleehammer** [comment]
If you are using unixODBC this should be fixed by b126ffb on the master thread.

If you are *not* using unixODBC and your driver requires a SQLWCHAR size other than 2-bytes let me know.  I'm going to need to make this configurable but since it works for unixODBC and Windows I'll start there.

I'll release this as 3.1.0 when I've fixed a couple of other bugs.

**Comment by mpwoodward** [comment]
Thanks!
