### ISSUE TITLE
Having to use full qualified names for querys.

### ISSUE THREAD

**Issue by stylneo** [mkleehammer/pyodbc#413]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.1 (Anaconda 4.4.0) 64-bit
- pyodbc: 4.016
- OS: Win10 64bit
- DB: SQL Server 14
- driver: SQL Server 2017 14.0.1 (express)

### Issue
Not sure if this is or not intended behavior but despite specifying the database I want to work with in the connection string it seems I still have to use full qualified object names in my queries (e.g: [database].[dbo].[table_name] for selects). I can get around this by executing an "USE database" command but it seems weird to have to do it since I set the target database on connect.

**Comment by gordthompson** [comment]
Please show us your connection string or DSN settings,

**Comment by stylneo** [comment]
Driver={SQL Server};Server=my_machine\SQLEXPRESS;Initial Catalog=TestDB;Integrated Security=True;

**Comment by keitherskine** [comment]
Perhaps try `Database` instead of `Initial Catalog` ?  (https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-2017)

Also, `{SQL Server}` sounds like it a very old driver.  You might want to try installing and using the latest SQL Server drivers. (https://www.microsoft.com/en-us/download/details.aspx?id=53339 or https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-2017)

**Comment by v-chojas** [comment]
`SELECT DB_NAME()` will let you know whether you have switched to the correct database.

**Comment by stylneo** [comment]
Using `Database` instead of `Initial Catalog` did the trick. Many thanks!
