### ISSUE TITLE
TypeError: can't pickle pyodbc.Connection objects

### ISSUE THREAD

**Issue by suganya301** [mkleehammer/pyodbc#433]
Environment
Python: 2.7
pyodbc: 4.0.23
OS: UBUNTU (version16.4)
DB: SQL Azure(12.0.2000.8)
driver: Microsoft ODBC Driver 17 for SQL Server

issue:
am getting below error while using multiprocessing.pool with pyodbc connection object.

File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: can't pickle pyodbc.Connection objects

**Comment by v-makouz** [comment]
Do you have repro code? I want to try and see if I can reproduce this

**Comment by mkleehammer** [comment]
I'm not sure it makes sense to pickle a connection.  It isn't possible for the actual socket, pipe, etc. to be pickled (the driver has these, not pyodbc) and sent to the child process, so the only option would be to save the connection string and make a new connection when unpickled.

I don't want to keep the original connection string in memory any longer than I have to since it may have sensitive information like a password.

I think it would be better if you pickled the connection string instead and had the called function create a new connection.
