### ISSUE TITLE
Arbitrary connect keywords are ignored. Where - by PyODBC or the server?

### ISSUE THREAD

**Issue by felix-hilden** [mkleehammer/pyodbc#449]
### Environment
- Python: x64
- pyodbc: 4.0.23
- OS: Windows 10
- DB: SQL Server
- driver: ODBC Driver 17 for SQL Server

### Issue
I noticed that I could write any keyword arguments to pyodbc.connect() and still get a valid connection as long as all the needed arguments are present and valid. I couldn't find proper documentation on the ignoring.

PyODBC documentation mentions that the keyword arguments are parsed into a connection string. Is this ignoring done by pyodbc or the database server? I was looking into passing additional arguments when connecting from Linux as opposed to Windows (TDS_Version). Maintenance and programming style aside, I wonder if this is documented behavior.

**Comment by gordthompson** [comment]
A quick test under Linux confirms that pyodbc simply constructs the connection string using *all* supplied keyword arguments and passes that to the driver manager:

```python
cnxn = pyodbc.connect(
    Bacon="yummy",
    Driver="FreeTDS",
    Server="192.168.1.128",
    Port="49242",
    Database="myDb",
    TDS_Version="7.3",
    UID="sa",PWD="whatever"
)
```

```
[ODBC][3738][1535029010.553899][SQLDriverConnectW.c][290]
        Entry:
            Connection = 0xef21d0
            Window Hdl = (nil)
            Str In = [Bacon=yummy;Driver=FreeTDS;Server=192.168.1.128;Port=49242;Database=myDb;TDS_Version=7.3;UID=sa;PWD=whatever;][length = 109]
```

It is up to the driver to ignore (or complain about) connection string arguments that it doesn't understand.

That makes sense, since pyodbc has to deal with many different ODBC drivers with many different connection string arguments, so it doesn't really know (or particularly care) if the keyword arguments are valid for the ODBC driver in question. It just passes along what it was given in the `.connect` call.

**Comment by felix-hilden** [comment]
Thank you for the test! Indeed that seems like a good rationale.
May I ask for the method or tool you used in the test?

**Comment by gordthompson** [comment]
I just did an [ODBC trace log on Linux](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting:-Generating-an-ODBC-trace-log#linux). IIRC, Windows ODBC logs don't include the connection string text.

**Comment by mkleehammer** [comment]
To be clear, pyodbc does not examine the connection string at all.  If you supply a single string, it simply passes it along to the driver.  (Well, the driver manager which forwards it to the driver.)

It accepts most keywords and adds them to the connection string only as a convenience.

There are a few keywords that it explicitly uses, like autocommit.  In hindsight it would have been better to accept a dictionary of connection string keywords instead of taking any keyword in the constructor.
