### ISSUE TITLE
SQL Server BACKUP DATABASE statement fails silently

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#471]
(Prompted by investigation into [this Stack Overflow question](https://stackoverflow.com/q/52686705/2144390).)

Python 3.6.4 64-bit, pyodbc 4.0.24, Windows 7

The following Python/pyodbc code fails silently. No error is thrown, but no backup file is produced either.

```python
import pyodbc


def get_conn_str():
    conn_str = (
        r'DRIVER=ODBC Driver 17 for SQL Server;'
        r'SERVER=.\SQLEXPRESS;'
        r'DATABASE=myDb;'
        r'Trusted_Connection=yes;'
    )
    return conn_str


pyodbc.pooling = False

cnxn = pyodbc.connect(get_conn_str(), autocommit=True)
crsr = cnxn.cursor()

crsr.execute(
        r"BACKUP DATABASE [myDb] TO  DISK = N'C:\__tmp\mybackup.bak' WITH NOFORMAT, NOINIT,  NAME = N'mybackup.bak', SKIP, NOREWIND, NOUNLOAD,  STATS = 10"
    )

crsr.close()
cnxn.close()
```

ODBC log: [pyodbc_no_va.txt](https://github.com/mkleehammer/pyodbc/files/2460289/pyodbc_no_va.txt)

However, the following VBScript does create the .bak file.

```vb
Option Explicit
Dim conn
Set conn = CreateObject("ADODB.Connection")
Dim connStr
connStr = _
        "DRIVER=ODBC Driver 17 for SQL Server;" & _
        "SERVER=.\SQLEXPRESS;" & _
        "DATABASE=myDb;" & _
        "Trusted_Connection=yes;"
conn.Open connStr

conn.Execute("BACKUP DATABASE [myDb] TO  DISK = N'C:\__tmp\mybackup.bak' WITH NOFORMAT, NOINIT,  NAME = N'mybackup.bak', SKIP, NOREWIND, NOUNLOAD,  STATS = 10")

conn.Close
```

ODBC log: [adodb_ok.txt](https://github.com/mkleehammer/pyodbc/files/2460290/adodb_ok.txt)

**Comment by v-makouz** [comment]
I am able to repro and I'm investigating this, will keep you updates as I find out more

**Comment by v-makouz** [comment]
After looking into it, I see that when requesting the DB backup the server sends multiple results containing messages about what percentage of the backup is complete, so if the client application doesn't wait for all of them and closes the connection after the first one, the backup is aborted. The client application will not see the error sent by the server, because it already closed the connection and is no longer listening for it.

The easiest way to fix it is to add
```
while (crsr.nextset()):
    pass
```

right after the execute command, internally this will keep calling SQLMoreResults until the server is done with the backup

**Comment by gordthompson** [comment]
Thanks, that seems to do the trick. I wasn't sure it would work if the `.nextset()` call happened before the database had actually sent the next "progress" result, as might happen if the database was large, but I ran a few tests and that does not appear to be an issue. Maybe there is something in the ODBC (or TDS?) "conversation" to indicate that the process is not yet complete so even though there isn't another result available *right now* there may be another one shortly.

**Comment by v-makouz** [comment]
In TDS there is an indication that the result set is not final. As I understand in ODBC the way to check is to call SQLMoreResults or SQLFetchScroll which would return SQL_NO_DATA if there are no more results. 

But for the progress reporting when backing up the DB, the messages come as DiagRecs, so they don't have result sets per se, so one can't SQLFetch them that's why for this specific case I believe only SQLMoreResults is useful

**Comment by mkulasi** [comment]
> After looking into it, I see that when requesting the DB backup the server sends multiple results containing messages about what percentage of the backup is complete, so if the client application doesn't wait for all of them and closes the connection after the first one, the backup is aborted. The client application will not see the error sent by the server, because it already closed the connection and is no longer listening for it.
> 
> The easiest way to fix it is to add
> 
> ```
> while (crsr.nextset()):
>     pass
> ```
> 
> right after the execute command, internally this will keep calling SQLMoreResults until the server is done with the backup

Thank you mate, this solved my problem in 2020 👍
