### ISSUE TITLE
How to obtain the key value of the last executed insert? lastrowid doesn't exist it seems.

### ISSUE THREAD

**Issue by MostHated** [mkleehammer/pyodbc#473]
Hello all,
 I decided to also add MS SQL Server to my application and it was recommended to use pyodbc, so that was what I went with. I have ran into an issue though, with MySQL and another db connection package I was able to use cursor.lastrowid, which would let me do an insert in one table and the be able to insert more data into another linked table by the ID. I got the error that lastrowid didn't exist, so I went through the [documentation here](https://github.com/mkleehammer/pyodbc/wiki/Cursor) but I did not see anything that would really work in place of what I am trying to accomplish. 

Does anyone know of how I can go about getting the last inserted row ID so that I can continue on with inserting the data I need to based on what the prior insert's ID was?

Thanks,
-MH

**Comment by v-chojas** [comment]
It depends on the exact situation and schema, but if you are using identity columns then try the solutions at https://stackoverflow.com/questions/42648/best-way-to-get-identity-of-inserted-row .

**Comment by mkleehammer** [comment]
Do be careful here - SQL Server's ODBC driver seems to package everything in such a way that it creates a new scope, so IIRC I couldn't use just `@IDENTITY`.  @v-chojas Is there any public information on the way SQL Server packages queries with parameters?  About 15 years back I thought it used a stored procedure under the covers which is why it didn't work.

**Comment by v-chojas** [comment]
I believe it is still executed in a stored procedure context.
