### ISSUE TITLE
Query with parameters doesn't work, after adding output converter to connection

### ISSUE THREAD

**Issue by LemyDanger76** [mkleehammer/pyodbc#493]
### Environment

- Python: 2.7
- pyodbc: python-pyodbc-4.0.24-3.19.src
- OS: Suse 42.3
- DB: Informix
- driver:informixodbc

### Issue
def handle_type_bigint(dto_value):
   bigint = struct.unpack("@q", dto_value)[0]
   return bigint

connection.add_output_converter(-114, handle_type_bigint)

def queryAll(cursor, tableName):
   """ Returns list of dic with columns name as key """
   cursor.execute(
       " SELECT * FROM ? LIMIT 10", tableName
   )

causes the error :
cursor.execute("SELECT * FROM ? LIMIT 4", tableName)
pyodbc.Error: ('HY000', 'The driver did not supply an error!')

The issue appears only after I added add_output_converter .
If I send the whole sql query as string it works.
I'd like to have it working with params.

**Comment by gordthompson** [comment]
An [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting:-Generating-an-ODBC-trace-log) might help shed light on the problem, but generally speaking we cannot count on being able to use query parameters to specify table/column *names*.

**Comment by mkleehammer** [comment]
This is baffling.  You are saying you can read values if you don't add a converter?

The only difference I can think of is that when you add a converter, the data is read using SQLGetData as `SQL_BINARY`.  Perhaps the driver refused to give us the data as binary?

The problem here is that I have to tell the database that I want the data in some format.  Perhaps I could use the type `-114`.  Are you able to test that yourself?  (I'm not sure if you do a lot of C++ programming.)

Unfortunately I don't have Informix.  I'll see if I can reproduce this using PostgreSQL or SQL Server. I'm pretty sure one of them has a type that doesn't coerce to binary.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
