### ISSUE TITLE
[Description] Internal size of description gives precision 

### ISSUE THREAD

**Issue by jensgoemaere** [mkleehammer/pyodbc#521]
The internal size field of the description of a cursor gives the precision of the column instead of the number of bytes:

cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER=serverX;DATABASE=DataBaseY;')
cursor = cnxn.cursor()
data = cursor.execute("""
           SELECT TOP (1000) *
           FROM TableZ
           """).fetchall()
description = pd.DataFrame(np.matrix(cursor.description))
description[3]==description[4]

**Comment by v-makouz** [comment]
Can you provide database type and the table schema?

**Comment by jensgoemaere** [comment]
> Can you provide database type and the table schema?

I am using Microsoft SQL Sever.
[description.xlsx](https://github.com/mkleehammer/pyodbc/files/2851969/description.xlsx)

**Comment by gordthompson** [comment]
The code [here](https://github.com/mkleehammer/pyodbc/blob/84e9d5d5a77427a0b8ab0b5973a391951c2a4528/src/cursor.cpp#L257) certainly does appear to always write the same value into the `internal_size` and `precision` columns.

**Comment by v-chojas** [comment]
The DB-API specification does not have any detailed description of those attributes and https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/column-size suggests that precision is the same as the length of the column in characters or bytes for non-numeric types, so it would appear that this behaviour is by design.

**Comment by gordthompson** [comment]
Hi @v-chojas 

Comments in the code immediately preceding the above reference suggest that in this case "by design" may well translate to "the best we can hope to do given the vagaries of various ODBC drivers". The problem is that, at least for SQL Server ODBC, the `internal_size` values are just plain wrong.

```python
print('driver version ' + cnxn.getinfo(pyodbc.SQL_DRIVER_NAME) + '  ' + cnxn.getinfo(pyodbc.SQL_DRIVER_VER))
# driver version msodbcsql17.dll  17.02.0000

crsr = cnxn.cursor()
crsr.execute(CREATE TABLE ##tmp (id INT PRIMARY KEY, txt NVARCHAR(10), d DECIMAL(18, 4)))
crsr.execute("SELECT * FROM ##tmp")
pprint(crsr.description)
# (('id', <class 'int'>, None, 10, 10, 0, False),
#  ('txt', <class 'str'>, None, 10, 10, 0, True),
#  ('d', <class 'decimal.Decimal'>, None, 18, 18, 4, True))
```

`int` reports a precision of 10 because it is a subset of `decimal(10, 0)`, but its internal size is 4 bytes, not 10. `nvarchar(10)` has an internal size of 20 bytes, not 10. And a `decimal(18, 4)` column has an internal size of [9 bytes](https://docs.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-2017), not 18.

Maybe `description` should just return `None` for the `internal_size` column, since 

1. it's optional anyway, and
2. the whole "length of the column in characters or bytes" thing is another source of potential confusion depending on the particular string encoding involved.

**Comment by v-chojas** [comment]
You are talking about the number of bytes in the TDS/internal storage representation, which is really irrelevant to an application and not something ODBC provides nor even needs to concern itself with; this is also by design. The column size is more useful to an application, which is why SQLDescribeCol (where those values come from) provides it.

There is no harm in leaving it alone because changing it can only break any existing applications that were using that attribute.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open if necessary.
