### ISSUE TITLE
Issues with UTF-16 strings on 64 bit versions

### ISSUE THREAD

**Issue by rclough** [mkleehammer/pyodbc#57]
I know I commented on this issue back on google code, but never received a response. https://code.google.com/p/pyodbc/issues/detail?id=78

Basically it looks like it was "fixed" at some point, and then the patch reverted some time around 2014. I checked this new github repository, and the problematic line still appears to be there:

https://github.com/mkleehammer/pyodbc/blob/master/src/getdata.cpp#L319

You can glean plenty of details from that first link, but I'll quote some in case google code disappears some day:

```
What steps will reproduce the problem?
1 Setup odbc correctly.
2 Execute the following:
 import pyodbc
 database = pyodbc.connect('DSN=localhost')
 cursor = database.cursor()
 cursor.execute('SHOW CREATE TABLE mysql.users')
 print cursor.fetchall()
 cursor.close()
 database.close()
2 Notice the output being in UTF-16 in memory format, containing something
like this:
 [(u'\U00730075\U00720065', u'\U00520043\U00410045\U00450054\U00540020 ...

What is the expected output? What do you see instead?
Something readable in UTF-8, containing something like this:
...
`Host` char(60) COLLATE utf8_bin NOT NULL DEFAULT '',
`User` char(16) COLLATE utf8_bin NOT NULL DEFAULT '',
...

What version of the product are you using? On what operating system?
pyodbc-2.1.5-2.fc11.i586
unixODBC-2.2.14-2.fc11.i586
mysql-5.1.37-1.fc11.i586
mysql-libs-5.1.37-1.fc11.i586
mysql-server-5.1.37-1.fc11.i586
mysql-connector-odbc-5.1.5r1144-4.fc11.i586
```

```
I've had the same issue, which only seems to happen on 64-bit machines.

Here's my setup:
ubuntu 10.4 64-bit
pyodbc-2.1.7
unixODBC-2.2.11-21
freeTDS-0.82

Server:
MS SQL Server 2008

I've traced the problem back to a call to SQLGetData in getdata.cpp. The function doesn't seem to handle unicode strings correcty on 64-bit systems. Specifying a charset in the pyodbc.connect() call doesn't fix it. I was able to fix it by mapping all unicode character types to SQL_C_CHAR, I'm attaching a diff of the fix.

Daniel Erickson
Concentric Sky, Inc.
www.concentricsky.com
```

Contents of patch:

```
diff --git a/src/getdata.cpp b/src/getdata.cpp
index a487ae3..660116b 100644
--- a/src/getdata.cpp
+++ b/src/getdata.cpp
@@ -262,7 +262,8 @@ GetDataString(Cursor* cur, int iCol)
     case SQL_WCHAR:
     case SQL_WVARCHAR:
     case SQL_WLONGVARCHAR:
-        nTargetType  = SQL_C_WCHAR;
+        //nTargetType  = SQL_C_WCHAR;
+        nTargetType  = SQL_C_CHAR;
         break;
         
     default:
```

**Comment by mkleehammer** [comment]
Well, the actual problem is that the MySQL driver (along with plenty of others) doesn't follow the specification at all.  In particular I believe it is writing UTF_8 data and calling it SQL_WCHAR which it is not.  SQL_WCHAR is almost always a 2-byte value (but can be 4).  It should only write UTF_16 to these buffers.  I think they are trying to differentiate between some 1-byte "native" encoding and UTF_8 Unicode by using SQL_CHAR for one and SQL_WCHAR for the other, but that is completely wrong.  I would guess they don't want to spend the time converting from UTF_8 on disk to UTF_16.

I'm currently adding two values to connections specifically for the badly behaved drivers like MySQL:
* char_encoding - The encoding to use when receiving SQL_CHAR, which I'll default to UTF_8.
* wchar_encoding - The encoding to use when receiving SQL_WCHAR, which I'll default to UTF_16.

If I'm reading this correctly then you would set wchar_encoding to UTF_8 when using MySQL.

How does that sound?

**Comment by rclough** [comment]
You certainly know a lot more than me, I don't actually understand the root issue, nor why this patch works. I just know that when I patched pyodbc to match the above, it worked for me. 

Personally I use it for Vertica, not MySQL, but same problem/symptoms/solution. I'd be happy to test any new solutions

**Comment by mkleehammer** [comment]
I'm going to close this to replace with #112 so all discussions can be gathered in one place.  Please subscribe to that one for updates.

**Comment by selwyth** [comment]
I have the same issue described here, and downgrading pyodbc to 3.0.9 solved it for me. Not clear to me why it did.
