### ISSUE TITLE
Issues with binding parameters for large SQL Server queries

### ISSUE THREAD

**Issue by KYDronePilot** [mkleehammer/pyodbc#603]
#### Old
- Python: 2.7.2 (32 bit)
- pyodbc: 3.0.5

#### New
- Python: 3.7.4 (64 bit)
- pyodbc: 4.0.27

#### Same
- OS: Windows 10 1903
- DB: SQL Server 13.0.5216.0
- driver: SQL Server Native Client 11.0 (2011.110.6540.00)

### Issue

I am upgrading some old Python 2.7 code to Python 3.7 and ran into a very large query that is run
using pyodbc. It binds 28 parameters.

In the version of pyodbc I am running in Python 2.7, the query would take a little over a minute to
run, but in the latest version of pyodbc, I am unable to successfully run the query, as the tempdb
runs out of space before it can  complete. The longest it was able to run before the database
errored out was approximately 20 minutes.

I read the article in the wiki about difficulties binding parameters using SQLBindParameter, but am
confused as to why the query used to work in the older version of pyodbc. Did parameters used to be
formatted directly into the query or handled in some other way in that version?

As a side note, if I manually insert the parameters and run the query with pyodbc, it completes in
the normal amount of time (little over a minute). To further verify the issue had to do with
variable binding, I tried adding the variables back into the query a few at a time and the execution
time increased with each addition.

**Comment by v-makouz** [comment]
Do you have a repro app that we could try?

**Comment by KYDronePilot** [comment]
Unfortunately not. The code is closed source and the query is closely coupled with the database design; not something that could be easily reproduced.

**Comment by v-chojas** [comment]
Could you post an ODBC trace?

**Comment by KYDronePilot** [comment]
The trace can be found [here](https://pastebin.com/raw/AHax2V6Q).

Note: this includes everything from when the query was executed to when I stopped it (about a minute after it started; it wasn't producing any more log info and would have eventually errored out).

**Comment by v-chojas** [comment]
I assume you censored the query, because the driver would probably not want to execute an empty string.

Could you also post a trace of the working version, or at least the part up to the execute?

The most relevant change in Python between 2 and 3 is the string vs. bytes difference

**Comment by KYDronePilot** [comment]
That may very well be the issue, because I didn't have to censor anything from that log. The text I posted was exactly what it outputted.

[Here](https://pastebin.com/raw/sEdEfiSt) is a trace of it working in Python 2.7 (from when the query was executed to before it finished executing). I censored the table/column names, but left the structure of the query it displayed in tact.

**Comment by v-chojas** [comment]
Thanks, that comparison is very useful. But given the fact that it prepares successfully and reports 28 parameters, I suspect the empty string being displayed might just be an artifact of the logging and not the actual problem.

The other difference can be attributed to the bytes vs characters difference in Python; all the string parameters are being bound as narrow characters in 2.x, and wide (Unicode) in 3.x. "tempdb runs out of space" might just be the result of making the server do the processing in wide characters too and thus require more memory/disk, especially if it was already close to the limit before.

Could you try using the [ODBC Driver 17 for SQL Server ](https://www.microsoft.com/en-us/download/details.aspx?id=56567) ? That can help indicate whether the problem is in the SQLNCLI11 driver (which is rather old, and a considerable number of bugs fixed since) not handling Unicode correctly, or something else.

**Comment by KYDronePilot** [comment]
I've updated and am now using that driver.

I ran the query in the Python 3 environment and had the same issue. I stopped it about 10 minutes in to prevent it from running the server out of space. The trace matched the Python 3 trace (except for addresses) with the old driver. Still no SQL being displayed.

I also ran on the Python 2 environment and got similar results to when I was using the old driver. It ran successfully in about a minute's time and the ODBC trace was the same (once again, except for addresses).

I'm doubtful that the issue of tempdb running out of space is caused by strings being bound as wide characters, since the old query runs in, at most, 2 minutes, while the new query can run for upwards of 20 minutes before erroring out (due to tempdb running out of space). Unless having to process both narrow and wide causes an exponential growth in the resources/space needed.

**Comment by v-chojas** [comment]
Without providing a minimal repro app, there is not much additional assistance I can offer. The change of driver suggests that the problem is not originating from the driver. If your server was already close to the limits with memory, thus the double-length wide characters may be going over and forcing the server to use the tempdb for storage instead, hence running out of space.

You can also use something like Wireshark to inspect the communication between the client and server,

**Comment by KYDronePilot** [comment]
Is there any way to specify that the query should bind the strings as narrow characters to see if that is the issue? I tried encoding the string parameters before running the query, but am getting the SQL Server error: "Implicit conversion from data type varchar to varbinary is not allowed"

**Comment by gordthompson** [comment]
> Is there any way to specify that the query should bind the strings as narrow characters

You could try using [setinputsizes](https://github.com/mkleehammer/pyodbc/wiki/Cursor#setinputsizeslist_of_value_tuples) to specify the parameters in question as `pyodbc.SQL_VARCHAR`.

**Comment by KYDronePilot** [comment]
That seems to fix the issue. Thank you all for helping me figure it out.

One other question: Is there a constant that can be placed in the list for `setinputsizes` that tells pyodbc to figure out that parameter type on its own? I would like to be able to explicitly set the input type for strings, but let pyodbc handle other types as it normally would.

**Comment by v-chojas** [comment]
`None` will use the default.

**Comment by KYDronePilot** [comment]
Ok, thanks again.
