### ISSUE TITLE
Inserting 10 million records from dataframe to mssql

### ISSUE THREAD

**Issue by zacqed** [mkleehammer/pyodbc#619]
I am trying to insert 10 million records into a mssql database table. After reviewing many methods such as fast_executemany, to_sql and sqlalchemy core insert, i have identified the best suitable way is to save the dataframe as a csv file and then bulkinsert the same into mssql database table. The implementation code is as follows:

```
new1.to_csv(r'C:\Users\XXXXX\desktop\appfile3.csv', sep=',', index=False) 
import pyodbc
conn = pyodbc.connect("driver={ODBC Driver 17 for SQL Server};server=LAPTOP-XXXX;database=XXXX;Uid=google;Pwd=XXXX;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;")
crsr = conn.cursor()    
sql = "BULK INSERT [cashflow_gen1] FROM 'C:\\Users\\XXXXX\\desktop\\appfile3.csv' WITH (FIRSTROW = 2,FIELDTERMINATOR = ',', ROWTERMINATOR = '\n')"
crsr.execute(sql)
conn.commit()
crsr.close()
```
The aforesaid approach substantially reduces the total time, however i am trying to find ways to reduce the insert time even further. Following are the thought processes i am working back with
1. The major time taken is in writing the CSV (approx 8 minutes), instead of writing a csv file, is there a possibility to stream the dataframe as CSV in memory and insert it using BULK INSERT
2. Is there a possibility to use multiprocessing or multithreading to speed up the entire csv writing process or bulk insert process.

I have read through 100's of posts on stack and other forums, however unable to figure out a solution. Any help is much appreciated.

The environment details are as follows:
PYODBC: 4.0.27
SQLALCHEMY: 1.3.8
MSSQL : SQL Server 2017
Pandas: 0.25.1

**Comment by gordthompson** [comment]
Also being discussed on Stack Overflow [here](https://stackoverflow.com/q/57842123/2144390).

**Comment by v-chojas** [comment]
How did those 10M records end up in memory in the first place? I think rather than focus on this one step of your process, it would be better to think about the whole process and do it such that you don't have to move the data around as much.

Some info found here suggests that SQL Server may be willing to read from a named pipe instead of an on-disk file, although I'm not sure how you would create one in Python: https://stackoverflow.com/questions/2197017/can-sql-server-bulk-insert-read-from-a-named-pipe-fifo/14823428

**Comment by Harshitg** [comment]
@v-chojas - Thanks this looks interesting, i will try to figure out how we can usage named pipe in python.

**Comment by boumboum** [comment]
Please be aware that BULK INSERT is only working with files visible from the server where sqlsrvr.exe is located. (i.e. if you have a remote server and the CSV file is on your machine, than it won't work).
On the other hand for BULK INSERT there must be a physical file. (See [https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15)
So filestream would not fit.

**Comment by mgsnuno** [comment]
@zacqed I have a similar situation and went through the same. I'm using dask to write the csv files. It's very fast.

**Comment by boumboum** [comment]
@mgsnuno: My remark is still valid. If the machine where the CSV file is located not visible from the mssql server machine, than you cannot use bulk insert.
bcp would do but you have to have bcp installed on that machine and you have to open a new process to load bcp.
That's why a bcp implementation within pyodbc would be more than welcome. (although fast_executemany has done in that extent already a nice job)

**Comment by mgsnuno** [comment]
@boumboum I have an azure-mssql server that bulk inserts from azure blob by setting the following (only run once, otherwise you have to run the `DROP` commands the second time):

```sql
CREATE MASTER KEY ENCRYPTION BY PASSWORD= 'password_here'

-- DROP EXTERNAL DATA SOURCE abfs_source
-- DROP DATABASE SCOPED CREDENTIAL abfs_credential

CREATE DATABASE SCOPED CREDENTIAL abfs_credential
WITH IDENTITY = 'SHARED ACCESS SIGNATURE',
SECRET = 'sp=rl&st=2020-08........';

CREATE EXTERNAL DATA SOURCE abfs_source
    WITH (
        TYPE = BLOB_STORAGE,
        LOCATION = 'https://storageaccount.blob.core.windows.net',
        CREDENTIAL = abfs_credential
    );
```

I don't know how to use `CREATE EXTERNAL DATA SOURCE` to connect to your local machine but thought it would be relevant to leave this as reference.
