### ISSUE TITLE
how to use subprocess.Popen with pyodbc?

### ISSUE THREAD

**Issue by ericwang321** [mkleehammer/pyodbc#655]
**1. Environment:**
    Python: Python 3.6.8
    pyodbc: pip3 install pyodbc #pyodbc-4.0.27
    OS: ubuntu 18.04 64bit
    DB:windows server 2012 R2 MSSQL 2012
    driver:Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1

**2. Issue**
p3.py
```python 
import pyodbc 
import random
import os
import subprocess

list1 = [
    ('2019-10-14 10:48:45',3,'n12','/home/toor/1_192.168.1.2_191013104845_33.jpg'),
    ('2019-10-14 10:48:45',3,'n12','/home/toor/1_192.168.1.2_191013104845_33.jpg'),
    ('2019-10-14 10:48:45',3,'n12','/home/toor/1_192.168.1.2_191013104845_33.jpg'),
    ]
def uploaddb(list1):
  conn = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                    'Server=192.168.1.10;'
                    'Database=tms;'
                     'Trusted_Connection=no;'
		     'UID=tmsdb;'
		     'PWD=123')
  cursor = conn.cursor()
  sqlconn = "INSERT into tmsdb.dbo.ip2(time,cnt,ip,path) VALUES(? ,? ,? ,?)"
  number = cursor.executemany(sqlconn,list1)
  conn.commit()

if __name__ == "__main__":
  subprocess.Popen(uploaddb(list1))
```

when run python3 p3.py,the following error is displayed
**_TypeError: 'NoneType' object is not iterable_**

how deal with it?
Thanks for any suggestion.

**Comment by v-makouz** [comment]
uploaddb() doesn't return anything, so the value of "uploaddb(list1)" is `None`.
I'm not familiar with subprocess.Popen(), but it must be expecting something as a parameter(s)

**Comment by gordthompson** [comment]
[subprocess](https://docs.python.org/3/library/subprocess.html) is for creating a separate *process*, which is effectively asking the computer's operating system to launch a separate application. The operating system knows about the Python interpreter that is running your main script, but it doesn't know about the script's internals and (almost certainly) doesn't know anything about the `uploaddb()` function.

It looks like you might be wanting to start a separate *thread*, which is a parallel execution path within the same process. In that case you may want to search around for a tutorial on threading in Python. Since your issue (at the moment) really does not relate to pyodbc *per se* you might want to try asking on [Stack Overflow](https://stackoverflow.com/questions/tagged/python).

**Comment by ericwang321** [comment]
**_thanks for your replies_**
The following is part of the modified script. **_Some places have incorrect syntax and are being_** resolved.
```python
def uploaddb(list1):
   ....
  i = 'done'
  return i

if __name__ == "__main__":
  rel = uploaddb(list1)
  print ('1',rel)
  subprocess.Popen(print(rel),shell=True)
```
I will temporarily **_close this issue later_**, and when it is **_completely resolved, I will correct it._**

**Comment by ericwang321** [comment]
below modified script，works.But it may be a bit inefficient
```python
def uploaddb(list1):
   ....
  i = 'done'
  return i

if __name__ == "__main__":
  rel = uploaddb(list1)
  os.environ['var']=str(rel) 
  subprocess.Popen('echo $var',shell=True)
```
**_thanks again_**
