### ISSUE TITLE
Support for DATABASE_URL

### ISSUE THREAD

**Issue by abitrolly** [mkleehammer/pyodbc#667]
DATABASE_URL is [12factor](https://www.12factor.net/backing-services) concept that is great for apps portability.

### "expected behavior"
```
conn = pyodbc.connect('mssql://user:pass@myhost/database')
```

### "observed behavior".
```
conn = pyodbc.connect(
    'Driver={SQL Server};Server=myhost;Database=database;UID=user;PWD=pass;Trusted_Connection=yes;'
)
```

**Comment by gordthompson** [comment]
Are you familiar with [SQLAlchemy](https://pypi.org/project/SQLAlchemy/)?

**Comment by mkleehammer** [comment]
I agree and try to use (most of) its rules of thumb.

First, note that 12-factor is recommending using *some* environment variable to keep the details out of the code but it doesn't have to be called anything in particular.   (Alternatively, if you really like the name, you can assign any string to it even thought it is called "URL", though I would use something like DATABASE_INFO or something.)

Second, pyodbc does not read, use, or modify the connection string.  It is defined by the ODBC specification and drivers, so it has to be whatever your ODBC driver manager and ODBC driver will accept.  I have no control over the format.  The value is simply passed to the driver manager unmodified.

I'm going to close this since there is nothing to change, but @gordthompson please reopen if I missed something.

**Comment by abitrolly** [comment]
@gordthompson do you mean I can just swap `pyodbc.connect` with [`sqlalchemy.create_engine`](https://docs.sqlalchemy.org/en/13/dialects/mssql.html#connecting-to-pyodbc) and all MS SQL specific queries will continue to work?

**Comment by abitrolly** [comment]
@mkleehammer `DATABASE_URL` convention is used by Heroku.

**Comment by gordthompson** [comment]
> all MS SQL specific queries will continue to work?

The vast majority of them would, and you would always have the option to drop back down to a raw pyodbc connection via

```python
cnxn = engine.raw_connection()
```

if necessary.
