### ISSUE TITLE
Not getting text from MS Access when cell is configured as lookup

### ISSUE THREAD

**Issue by TheMac** [mkleehammer/pyodbc#669]
Hello

I am trying to get the text from a cell that has been defined as a lookup function in Access. When I run my query I only receive the number for the row the text is placed in its tabel.

**Comment by gordthompson** [comment]
This is a limitation of working with Access via ODBC. You're getting the ID number (foreign key value) of the corresponding row in the lookup table because that what Access actually stores in the main table. When you work in the Microsoft Access UI you see the related text because that has been coded into the application layer.

However, the ODBC driver does not recognize the Lookup Field as "special" so you just get the numeric foreign key. You'll either have to do a separate lookup afterwards or create an SQL statement that does a JOIN on the lookup table.
