### ISSUE TITLE
App hangs for an extended period of time when >= 15 async requests are pending

### ISSUE THREAD

**Issue by bpaterni** [mkleehammer/pyodbc#694]
### Environment
- 64-bit
- Python: 3.6.6
- pyodbc: 4.0.28
- OS: Debian bullseye/sid
- DB: MS SQL Server
- driver: Microsoft ODBC Driver 17 for SQL Server

### Issue

pyodbc seems to handle async communication to SQL Server fine until >= 15 busy connections exist. I've been trying to track down the source of this issue for over a year, and so far the journey has led to pyodbc. For reference, [the previous support thread on the SQLAlchemy mailing list](https://groups.google.com/forum/#!msg/sqlalchemy/c1hql6jLk9c/2fGtvCYhBwAJ). At the request of Mike Bayer on that list, I've attempted to create [a MCRE of this issue](https://github.com/bpaterni/simple-blocking-eventlet) Included in the MCRE, is a test of the same async operation against postgresql-sqlalchemy. It can be seen that the same extended hang does not occur when using postgresql-sqlalchemy. The aim of this ticket is to achieve the same results when using MSSQL as the backend database.

Please let me know if additional information is needed.
ADVthanksANCE

**Comment by v-makouz** [comment]
Do you have a repro script?

**Comment by bpaterni** [comment]
Yes, most everything needed to reproduce the issue is in the project linked
above:

GitHub.com/bpaterni/simple-blocking-eventlet

By default, app.py will use the pyodbc-only mssql implementation to produce
15 parallel long-running queries. The hang should occur after the 15th
output of "pre busy mssql"


On Mon, Feb 3, 2020, 09:10 v-makouz <notifications@github.com> wrote :

**Comment by gordthompson** [comment]
I set this up under Python 3.7 on Windows just to see what I would get. The first couple of "pre busy mssql"s (3 or 4) appeared relatively quickly, but then it really bogged down. After an hour all I had was 6 of them:

```
C:\Users\Gord\git\simple-blocking-eventlet>pipenv run python app.py
Loading .env environment variables…
pre busy mssql
pre busy mssql
pre busy mssql
pre busy mssql
pre busy mssql
pre busy mssql
```

Checking the Activity Monitor in SSMS I saw:

![screenshot](https://i.stack.imgur.com/zbMVf.png)

Hope this helps.

**Comment by keitherskine** [comment]
Just a few random thoughts.  My suspicion is that this is more of an MSSQL issue than a pyodbc one.  As I understand it, the scenario described above involves creating multiple temporary tables of a million records each and then fetching a thousand records at a time from them, all in parallel.  For a start, I'm guessing these large parallel queries would put a lot of strain on SQL Server itself.  (I'd be interested to know how much memory and CPU were being used on @gordthompson 's laptop during his test, was it maxed out?).  What's more, the SQL query used to generate a sequence of records is not particularly efficient (essentially a massively recursive CTE).  This is not @bpaterni  's fault, SQL Server is just not particularly good at this kind of thing.  I suspect PostgreSQL is much better at this, and more efficient.  It may not even need to create a table of records at all, instead just generate the records on the fly.

Overall though, one other thing occurs to me about this scenario.  It seems to have something of a flavor of "streaming" data rather than "querying" data.  If so, perhaps this scenario is better suited to another technology altogether?

**Comment by gordthompson** [comment]
> (I'd be interested to know how much memory and CPU were being used on @gordthompson 's laptop during his test, was it maxed out?).

Nope. CPU at around 10% and Memory at about 67%. However, I am testing against SQLEXPRESS and its memory consumption is around 3 GB so it may be hitting the cap. (I don't remember offhand what the limits are.)

**Comment by keitherskine** [comment]
Gotcha, thanks @gordthompson .  As you say, it's possible SQLEXPRESS is running out of memory with those big tables.

FYI, I see PostgreSQL does indeed have a built-in function for [generating sequences](https://www.postgresql.org/docs/9.4/functions-srf.html), probably way more efficient than SQL Server's multiple [hacky](https://stackoverflow.com/a/33146869) methods.  This is one of the features on Brent Ozar's SQL Server [wishlist](https://www.brentozar.com/archive/2015/10/sql-server-features-id-like-to-see-postgresql-edition/) from way back in 2015.

**Comment by v-chojas** [comment]
As far as I know, pyODBC doesn't use ODBC drivers in async mode. If you could provide an ODBC trace, that would help to determine the cause of the issue.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
