### ISSUE TITLE
pyodbc fails to connect without dsn= kwarg

### ISSUE THREAD

**Issue by io-d** [mkleehammer/pyodbc#728]
## Expected behavior

Can connect using the `pyodbc.connect(dsn, Database=...)` syntax

## Actual behavior

Must connect using the `pyodbc.connect(dsn=dsn, Database=...)` syntax, which causes issues on other platforms (on macOS, this causes the connection string to be passed as though prepended by `dsn=`). 

## Details

Traceback:
```
  File "/home/coquest/tr/api/utils.py", line 115, in get_db
    db = g._db = pyodbc.connect(dsn, Database='CQ_SworderNetProductAnalysis', autocommit=autocommit)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
```

DSN:
```
				'Driver=SQL Server;'
				'Server=[redacted];'
				'DSN=CoquestDev;'
				'uid=[redacted];pwd=[redacted];'
```

## Environment

- Python: CPython 3.8.2
- pyodbc: 4.0.30
- OS: Debian 10
- DB: MS SQL Server
- driver: unixodbc + libmsodbcsql-17.5.so.1.1

**Comment by v-chojas** [comment]
In the connection string, you can specify either `DSN` or `Driver`, but not both; in the DSN itself, there should not be a `DSN` key either.

**Comment by gordthompson** [comment]
You seem to be confusing the notions of "DSN" and "connection string". A DSN is a named entry in your computer's ODBC DSN repository that contains the details required to make the connection. On Linux systems the DSN definitions are stored in two text files:

- System DSNs are usually stored in /etc/odbc.ini
- User DSNs are stored in ~/.odbc.ini

The "details required to make the connection" are the attributes that make up a connection string, e.g.,

```
gord@xubuntu64-nbk1:~$ cat ~/.odbc.ini 
[panorama]
DRIVER=ODBC Driver 17 for SQL Server
SERVER=192.168.0.187,49242
DATABASE=myDb

[mysql_sqla]
DRIVER=MySQL ODBC 8.0 ANSI Driver
SERVER=192.168.0.179
PORT=3307
DATABASE=sqla_test
```

As you can see, my ~/.odbc.ini file currently contains two DSN definitions: `panorama` and `mysql_sqla`. If I want to use one of them to connect I can do either

```python
cnxn = pyodbc.connect("DSN=panorama;UID=sa;PWD=_whatever_")
```

or

```python
cnxn = pyodbc.connect(DSN="panorama", UID="sa", PWD="_whatever_")
```

If I have a connection string defined as

```python
connection_string = (
    r"Driver=ODBC Driver 17 for SQL Server;"
    r"Server=192.168.0.187,49242;"
    r"Database=myDb;"
    r"UID=sa;PWD=_whatever_;"
)
```

then the following will *not* work ...

```python
cnxn = pyodbc.connect(dsn=connection_string)
```

... because unixODBC will go searching for a DSN entry with that (big long) "name" and will never find it. Instead, I just use

```python
cnxn = pyodbc.connect(connection_string)
```

**Comment by io-d** [comment]
> In the connection string, you can specify either `DSN` or `Driver`, but not both; in the DSN itself, there should not be a `DSN` key either.

Thank you. In the end this resolved my issue.

> because unixODBC will go searching for a DSN entry with that (big long) "name" and will never find it.

Yes, I am aware. Nonetheless, I had `dsn=connection_string` and it worked, which confused me.
