### ISSUE TITLE
Query hangs unpredictably

### ISSUE THREAD

**Issue by sebarti** [mkleehammer/pyodbc#787]
### Environment

- Python: 3.7 (32-bit)
- pyodbc:  4.0.30
- OS: Windows 10
- DB: SQL Server 2019
- driver: ODBC Driver 17

### Issue

I have a very strange behavior in that a query suddenly starts to hang (takes very long to complete) and I don't know why. I first thought this might be a SQL Alchemy issue (I'm using SQL Alchemy and pyodbc to talk to a SQL Server). It's super hard for me to reproduce because at some point it runs fine as usual (this might be the next day or even after a few hours).

Usually it is the pyodbc cursor that takes very long to return.

I discussed and investigated this here [#5389](https://github.com/sqlalchemy/sqlalchemy/issues/5389)

I thought that maybe someone here has an idea what could be going on. Some low level C stuff maybe?

Thanks for your help in advance!

**Comment by v-makouz** [comment]
Have you been able to reproduce this without SQL Alchemy? PyODBC mostly just calls ODBC APIs, I'm not aware of it doing anything that in and of itself would take a long time (other then call a lot of APIs). If you can catch this with ODBC trace on we can see if unusually large number of function calls is being made.

It may also be waiting on the server, if you can make this happen with Wireshark on you can see if it's waiting for the server or not

**Comment by v-chojas** [comment]
The fact that it is intermittent suggests packet loss. If SQL Alchemy uses the ODBC driver in MARS mode, packet loss-induced delays can be greatly compounded: https://github.com/microsoft/msphpsql/issues/1055

**Comment by sebarti** [comment]
@v-chojas Just so I get it right, does MARS help in this situation or make the situation worse? I have not enabled MARS atm. All our SQL Servers are indeed sitting on VMs. I'll try to hook up Wireshark as soon as the problem reappears and I'll check if the packets reach the server at all.

@v-makouz I copied the generated SQL statement (string) and passed the parameters to a pyodbc cursor without any sqlalchemy involvement and I was not able to reproduce. But as this problem is happening intermittent it's hard for me to reproduce.

Strange to seems that all other queries work and at other times the same query just works again, so it is not the connection to the server in general. Can you elaborate on that? I'm not a network expert at all ...

**Comment by v-chojas** [comment]
MARS will make delays caused by packet loss much worse. If you are not using it, and there is no need to, then don't.
Is there anything about the problematic query which is distinctive compared to the others? e.g. is is (textually) long, and/or returns many rows/columns?

**Comment by keitherskine** [comment]
On the face of it, @sebarti , this sounds like a straight SQL performance issue, rather than anything to do with SQLAlchemy or pyodbc.  If the database tables you're querying are large (millions of rows), this might be about SQL execution plans and their re-use (or not), which might explain the intermittent nature of the issue.  [Here](http://www.sommarskog.se/query-plan-mysteries.html) is one article that might help (although it does get into the weeds somewhat).  There are a number of other articles on the intertubes about SQL performance tuning, and it's not always about indexes.
Have you had a DBA look at the SQL generated by SQLAlchemy, and the execution plans generated by SQL Server?  When the SQL "hangs", what is SQL Server doing under the hood - lots of reads, lots of writes, or what?  If I were you, I would find a tame DBA to check out the SQL statements.

**Comment by sebarti** [comment]
Hi everyone. Sorry for the very late followup but the issue is has no longer appeared for a while now. I think it really just was SQL issue. Thanks for the help and advice anyway. I think you can close the issue.
