### ISSUE TITLE
Floating point exception (core dumped) error while connecting to mysql 5.6

### ISSUE THREAD

**Issue by jettify** [mkleehammer/pyodbc#81]
I am trying to test pyodbc==3.0.10 with mysql 5.6 but have following error:
```python
In [1]: import pyodbc

In [2]: pyodbc.connect('Driver={MySQL};Server=127.0.0.1;charset=UTF8;Database=test_pyodbc;User=root;')
[1]    5406 floating point exception (core dumped)  ipython
```
```bash
$ uname -a
Linux vagrant-ubuntu-vivid-64 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ mysql --version
mysql  Ver 14.14 Distrib 5.6.24, for debian-linux-gnu (x86_64) using  EditLine wrapper

$ apt --installed list | grep libmyodbc
libmyodbc/vivid,now 5.1.10-3 amd64 [installed]
```

Other databases works just fine (postgresql and sqlite).

**Comment by mkleehammer** [comment]
Unfortunately I'm just getting this so far: 
`pyodbc.Error: ('H', '[H] [unixODBC][ (0) (SQLDriverConnect)')`

One problem with MySQL is that it has never actually matched the ODBC API - it passes data however it feels instead of passing single byte data as SQLCHAR and Unicode data as UCS2 or UTF16 SQLWCHARs.  They are trying to be efficient, but you should really follow the specification or things are going to crash.  I'm working on some settings to handle this.

I don't think that is what you are seeing though, as it wouldn't be a floating point exception, but is something to keep in mind when we get past this.

**Comment by artemtsushko** [comment]
Have exactly the same problem in HDBC (Haskell)
I've got the same MySQL and libmyodbc versions

**Comment by andrewufrank** [comment]
i have the same issue with the same version of libmyodbc on an armhf cpu
libmyodbc/stable,testing,now 5.1.10-3 armhf [installed].
has anybody tried to recompile libmyodbc? does it help? i would be glad if i could get instructions which steps to do (debian8). thank you!

**Comment by jettify** [comment]
Just for the record, upgrade `libmyodbc` to 5.3.4 solves the issue for me.
