### ISSUE TITLE
Inserting into MS Access very slow

### ISSUE THREAD

**Issue by holzay** [mkleehammer/pyodbc#883]
### Environment

- Python: 3.8.7 32bit
- pyodbc: 4.0.30
- OS: Windows 10
- DB: MS Access 2016 (32Bit)
- driver: Microsoft Access Driver (*.mdb, *.accdb)

### Issue

When trying to insert 250.000 rows (123 columns) into an MS Access database it takes more than 30 minutes to insert the data. I realise that it can't happen instantly, but 30 minutes seems a bit excessive.

I'm inserting the data all at once as a list of tuples and I'm using _execute_.

**Comment by gordthompson** [comment]
Yes, multi-row INSERTs into an Access table using `.executemany()` can be slow, at least in part because pyodbc has to send an individual INSERT statement for each row being inserted. Also, the time required to insert rows is not linear:

![500_rows](https://user-images.githubusercontent.com/15894006/111845889-5a521700-88cb-11eb-8906-1349f0463df8.png)

so for rather large numbers of rows you could be waiting a very long time. In that case you'd be better off to

```
pip install pywin32
```

and use `win32com` to create an instance of MSACCESS.EXE, then use the equivalent of the VBA statement

```vbscript
DoCmd.TransferText acImportDelim, _
    "Gh_pyodbc_883 Import Specification", "gh_pyodbc_883", _
    "C:\Users\Gord\Desktop\gh_pyodbc_883.csv", False
```

For my test with 500 rows, using `.executemany()` to INSERT took 107 seconds while using `TransferText` from VBA took less than 5 seconds.

**Comment by mkleehammer** [comment]
Very nice gordthompson.  Thanks.
