### ISSUE TITLE
pyodbc returning bad unicode on 64bit debian gnu/linux

### ISSUE THREAD

**Issue by webe3** [mkleehammer/pyodbc#96]
I am running pyodbc 3.0.6-2+b1 on 64bit debian computers.  It is returning bad unicode for a field in a netezza database.  I have traced it down to GetDataString.  The sql type is coming in as SQL_WVARCHAR.  The data looks like this when I get it back:

(u'\u5942\u5020\u4c49\u5241\u4720...

when I change the code in GetDataString to use SQL_C_CHAR instead of SQL_C_WCHAR it works.

case SQL_WCHAR:
    case SQL_WVARCHAR:
    case SQL_WLONGVARCHAR:
        //TargetType  = SQL_C_WCHAR;
        nTargetType  = SQL_C_CHAR;
        break;

This is what I get:

("BY PILAR ...

**Comment by mkleehammer** [comment]
This is due to the driver incorrectly returning data as UTF8.  The ODBC specification requires non-ANSII values to be returned as SQLWCHAR and encoded as UCS-2 or UTF-16.  However, since drivers don't I've created #112 to allow pyodbc to be configured to handle these situations.

I'm going to close this to replace with #112 so all discussions can be gathered in one place.  Please subscribe to that one for updates.
