### ISSUE TITLE
segfault with sqlrelay

### ISSUE THREAD

**Issue by wood-chris** [mkleehammer/pyodbc#97]
Hi!

I've come across a segmentation fault when trying to use SQLRelay via odbc. I've set up a DSN which works directly using `isql`, but as soon as I try and connect using `pyodbc.connect` I get a segmentation fault. Hopefully the code I've pasted below will show what I mean.

```
$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0- amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final

$ more /etc/odbc.ini
[sqlrtest]
Description=Connection to SQL Relay
Driver=SQLRelay
Server=sqlrserver
Port=9000
Socket=/route/to/sqlrelay.sock
User=<user>
Password=<password>

$ isql sqlrtest
+---------------------------------------+
| Connected!                               |
|                                                  |
| sql-statement                           |
| help [tablename]                      |
| quit                                           |
|                                                  |
+---------------------------------------+
SQL>quit

$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> pyodbc.connect("DSN=sqlrtest")
Segmentation fault
```

**Comment by mkleehammer** [comment]
Well, I don't have that exact build of everything.  Can  you get a better trace of segfault so we can see what module it was in?  What happens when you call connect is that a bunch of calls are made to the ODBC driver manager which loads your drvier (sqlrealy in this case) and makes calls into it.

An ODBC trace might also prove useful.

I see that it works with isql, but that isn't really narrowing it down to where I should look.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
